package com.buoyantec.dao;

import com.buoyantec.dataobject.ClassDO;
import com.buoyantec.dataobject.ClassDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    long countByExample(ClassDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByExample(ClassDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByPrimaryKey(Long tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insert(ClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insertSelective(ClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    List<ClassDO> selectByExample(ClassDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    ClassDO selectByPrimaryKey(Long tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClassDO record, @Param("example") ClassDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExample(@Param("record") ClassDO record, @Param("example") ClassDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKeySelective(ClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKey(ClassDO record);
}