package com.buoyantec.dao;

import com.buoyantec.dataobject.collegesDO;
import com.buoyantec.dataobject.collegesDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface collegesDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    long countByExample(collegesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int deleteByExample(collegesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int deleteByPrimaryKey(Long tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int insert(collegesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int insertSelective(collegesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    List<collegesDO> selectByExample(collegesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    collegesDO selectByPrimaryKey(Long tcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") collegesDO record, @Param("example") collegesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByExample(@Param("record") collegesDO record, @Param("example") collegesDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByPrimaryKeySelective(collegesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_colleges
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByPrimaryKey(collegesDO record);
}