package com.buoyantec.dao;

import com.buoyantec.dataobject.grouprolerelationDO;
import com.buoyantec.dataobject.grouprolerelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface grouprolerelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    long countByExample(grouprolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByExample(grouprolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByPrimaryKey(Long tgrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insert(grouprolerelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insertSelective(grouprolerelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    List<grouprolerelationDO> selectByExample(grouprolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    grouprolerelationDO selectByPrimaryKey(Long tgrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") grouprolerelationDO record, @Param("example") grouprolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExample(@Param("record") grouprolerelationDO record, @Param("example") grouprolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKeySelective(grouprolerelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grouprolerelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKey(grouprolerelationDO record);
}