package com.buoyantec.dao;

import com.buoyantec.dataobject.news_classDO;
import com.buoyantec.dataobject.news_classDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface news_classDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    long countByExample(news_classDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByExample(news_classDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByPrimaryKey(Long tncId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insert(news_classDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insertSelective(news_classDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    List<news_classDO> selectByExample(news_classDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    news_classDO selectByPrimaryKey(Long tncId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") news_classDO record, @Param("example") news_classDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExample(@Param("record") news_classDO record, @Param("example") news_classDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKeySelective(news_classDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKey(news_classDO record);
}