package com.buoyantec.dao;

import com.buoyantec.dataobject.rightDO;
import com.buoyantec.dataobject.rightDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface rightDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    long countByExample(rightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByExample(rightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByPrimaryKey(Long trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insert(rightDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insertSelective(rightDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    List<rightDO> selectByExample(rightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    rightDO selectByPrimaryKey(Long trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") rightDO record, @Param("example") rightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExample(@Param("record") rightDO record, @Param("example") rightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKeySelective(rightDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKey(rightDO record);
}