package com.buoyantec.dao;

import com.buoyantec.dataobject.rolerightrelationDO;
import com.buoyantec.dataobject.rolerightrelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface rolerightrelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    long countByExample(rolerightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByExample(rolerightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByPrimaryKey(Long trrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insert(rolerightrelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insertSelective(rolerightrelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    List<rolerightrelationDO> selectByExample(rolerightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    rolerightrelationDO selectByPrimaryKey(Long trrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") rolerightrelationDO record, @Param("example") rolerightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExample(@Param("record") rolerightrelationDO record, @Param("example") rolerightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKeySelective(rolerightrelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKey(rolerightrelationDO record);
}