package com.buoyantec.dao;

import com.buoyantec.dataobject.schoolDO;
import com.buoyantec.dataobject.schoolDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface schoolDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    long countByExample(schoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int deleteByExample(schoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int deleteByPrimaryKey(Long tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int insert(schoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int insertSelective(schoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    List<schoolDO> selectByExample(schoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    schoolDO selectByPrimaryKey(Long tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") schoolDO record, @Param("example") schoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByExample(@Param("record") schoolDO record, @Param("example") schoolDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByPrimaryKeySelective(schoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByPrimaryKey(schoolDO record);
}