package com.buoyantec.dao;

import com.buoyantec.dataobject.schoolrightDO;
import com.buoyantec.dataobject.schoolrightDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface schoolrightDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    long countByExample(schoolrightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByExample(schoolrightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByPrimaryKey(Long tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insert(schoolrightDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insertSelective(schoolrightDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    List<schoolrightDO> selectByExample(schoolrightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    schoolrightDO selectByPrimaryKey(Long tsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") schoolrightDO record, @Param("example") schoolrightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExample(@Param("record") schoolrightDO record, @Param("example") schoolrightDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKeySelective(schoolrightDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schoolright
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKey(schoolrightDO record);
}