package com.buoyantec.dao;

import com.buoyantec.dataobject.tonecategory;
import com.buoyantec.dataobject.tonecategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface tonecategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    long countByExample(tonecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int deleteByExample(tonecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int deleteByPrimaryKey(String toId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int insert(tonecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int insertSelective(tonecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    List<tonecategory> selectByExample(tonecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    tonecategory selectByPrimaryKey(String toId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") tonecategory record, @Param("example") tonecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int updateByExample(@Param("record") tonecategory record, @Param("example") tonecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int updateByPrimaryKeySelective(tonecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    int updateByPrimaryKey(tonecategory record);
}