package com.buoyantec.dao;

import com.buoyantec.dataobject.userrolerelationDO;
import com.buoyantec.dataobject.userrolerelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userrolerelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    long countByExample(userrolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByExample(userrolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int deleteByPrimaryKey(Long turId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insert(userrolerelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int insertSelective(userrolerelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    List<userrolerelationDO> selectByExample(userrolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    userrolerelationDO selectByPrimaryKey(Long turId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") userrolerelationDO record, @Param("example") userrolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByExample(@Param("record") userrolerelationDO record, @Param("example") userrolerelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKeySelective(userrolerelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrolerelation
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    int updateByPrimaryKey(userrolerelationDO record);
}