package com.buoyantec.dao;

import com.buoyantec.dataobject.usergrouprelationDO;
import com.buoyantec.dataobject.usergrouprelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface usergrouprelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    long countByExample(usergrouprelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int deleteByExample(usergrouprelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int deleteByPrimaryKey(Long tugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int insert(usergrouprelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int insertSelective(usergrouprelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    List<usergrouprelationDO> selectByExample(usergrouprelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    usergrouprelationDO selectByPrimaryKey(Long tugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") usergrouprelationDO record, @Param("example") usergrouprelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByExample(@Param("record") usergrouprelationDO record, @Param("example") usergrouprelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByPrimaryKeySelective(usergrouprelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_usergrouprelation
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    int updateByPrimaryKey(usergrouprelationDO record);
}