package com.buoyantec.dao;

import com.buoyantec.dataobject.userrightrelationDO;
import com.buoyantec.dataobject.userrightrelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userrightrelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    long countByExample(userrightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByExample(userrightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int deleteByPrimaryKey(Long turId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insert(userrightrelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int insertSelective(userrightrelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    List<userrightrelationDO> selectByExample(userrightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    userrightrelationDO selectByPrimaryKey(Long turId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") userrightrelationDO record, @Param("example") userrightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByExample(@Param("record") userrightrelationDO record, @Param("example") userrightrelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKeySelective(userrightrelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_userrightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    int updateByPrimaryKey(userrightrelationDO record);
}