package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class attachmentDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public attachmentDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaIdIsNull() {
            addCriterion("ta_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaIdIsNotNull() {
            addCriterion("ta_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaIdEqualTo(Long value) {
            addCriterion("ta_ID =", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdNotEqualTo(Long value) {
            addCriterion("ta_ID <>", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdGreaterThan(Long value) {
            addCriterion("ta_ID >", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ta_ID >=", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdLessThan(Long value) {
            addCriterion("ta_ID <", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdLessThanOrEqualTo(Long value) {
            addCriterion("ta_ID <=", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdIn(List<Long> values) {
            addCriterion("ta_ID in", values, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdNotIn(List<Long> values) {
            addCriterion("ta_ID not in", values, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdBetween(Long value1, Long value2) {
            addCriterion("ta_ID between", value1, value2, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdNotBetween(Long value1, Long value2) {
            addCriterion("ta_ID not between", value1, value2, "taId");
            return (Criteria) this;
        }

        public Criteria andTuIdIsNull() {
            addCriterion("tu_id is null");
            return (Criteria) this;
        }

        public Criteria andTuIdIsNotNull() {
            addCriterion("tu_id is not null");
            return (Criteria) this;
        }

        public Criteria andTuIdEqualTo(Long value) {
            addCriterion("tu_id =", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdNotEqualTo(Long value) {
            addCriterion("tu_id <>", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdGreaterThan(Long value) {
            addCriterion("tu_id >", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tu_id >=", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdLessThan(Long value) {
            addCriterion("tu_id <", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdLessThanOrEqualTo(Long value) {
            addCriterion("tu_id <=", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdIn(List<Long> values) {
            addCriterion("tu_id in", values, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdNotIn(List<Long> values) {
            addCriterion("tu_id not in", values, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdBetween(Long value1, Long value2) {
            addCriterion("tu_id between", value1, value2, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdNotBetween(Long value1, Long value2) {
            addCriterion("tu_id not between", value1, value2, "tuId");
            return (Criteria) this;
        }

        public Criteria andTaFilenameIsNull() {
            addCriterion("ta_FileName is null");
            return (Criteria) this;
        }

        public Criteria andTaFilenameIsNotNull() {
            addCriterion("ta_FileName is not null");
            return (Criteria) this;
        }

        public Criteria andTaFilenameEqualTo(String value) {
            addCriterion("ta_FileName =", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameNotEqualTo(String value) {
            addCriterion("ta_FileName <>", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameGreaterThan(String value) {
            addCriterion("ta_FileName >", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("ta_FileName >=", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameLessThan(String value) {
            addCriterion("ta_FileName <", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameLessThanOrEqualTo(String value) {
            addCriterion("ta_FileName <=", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameLike(String value) {
            addCriterion("ta_FileName like", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameNotLike(String value) {
            addCriterion("ta_FileName not like", value, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameIn(List<String> values) {
            addCriterion("ta_FileName in", values, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameNotIn(List<String> values) {
            addCriterion("ta_FileName not in", values, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameBetween(String value1, String value2) {
            addCriterion("ta_FileName between", value1, value2, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFilenameNotBetween(String value1, String value2) {
            addCriterion("ta_FileName not between", value1, value2, "taFilename");
            return (Criteria) this;
        }

        public Criteria andTaFileuriIsNull() {
            addCriterion("ta_fileURI is null");
            return (Criteria) this;
        }

        public Criteria andTaFileuriIsNotNull() {
            addCriterion("ta_fileURI is not null");
            return (Criteria) this;
        }

        public Criteria andTaFileuriEqualTo(String value) {
            addCriterion("ta_fileURI =", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriNotEqualTo(String value) {
            addCriterion("ta_fileURI <>", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriGreaterThan(String value) {
            addCriterion("ta_fileURI >", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriGreaterThanOrEqualTo(String value) {
            addCriterion("ta_fileURI >=", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriLessThan(String value) {
            addCriterion("ta_fileURI <", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriLessThanOrEqualTo(String value) {
            addCriterion("ta_fileURI <=", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriLike(String value) {
            addCriterion("ta_fileURI like", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriNotLike(String value) {
            addCriterion("ta_fileURI not like", value, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriIn(List<String> values) {
            addCriterion("ta_fileURI in", values, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriNotIn(List<String> values) {
            addCriterion("ta_fileURI not in", values, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriBetween(String value1, String value2) {
            addCriterion("ta_fileURI between", value1, value2, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaFileuriNotBetween(String value1, String value2) {
            addCriterion("ta_fileURI not between", value1, value2, "taFileuri");
            return (Criteria) this;
        }

        public Criteria andTaDescIsNull() {
            addCriterion("ta_desc is null");
            return (Criteria) this;
        }

        public Criteria andTaDescIsNotNull() {
            addCriterion("ta_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTaDescEqualTo(String value) {
            addCriterion("ta_desc =", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescNotEqualTo(String value) {
            addCriterion("ta_desc <>", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescGreaterThan(String value) {
            addCriterion("ta_desc >", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescGreaterThanOrEqualTo(String value) {
            addCriterion("ta_desc >=", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescLessThan(String value) {
            addCriterion("ta_desc <", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescLessThanOrEqualTo(String value) {
            addCriterion("ta_desc <=", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescLike(String value) {
            addCriterion("ta_desc like", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescNotLike(String value) {
            addCriterion("ta_desc not like", value, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescIn(List<String> values) {
            addCriterion("ta_desc in", values, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescNotIn(List<String> values) {
            addCriterion("ta_desc not in", values, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescBetween(String value1, String value2) {
            addCriterion("ta_desc between", value1, value2, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaDescNotBetween(String value1, String value2) {
            addCriterion("ta_desc not between", value1, value2, "taDesc");
            return (Criteria) this;
        }

        public Criteria andTaUpdateIsNull() {
            addCriterion("ta_UpDate is null");
            return (Criteria) this;
        }

        public Criteria andTaUpdateIsNotNull() {
            addCriterion("ta_UpDate is not null");
            return (Criteria) this;
        }

        public Criteria andTaUpdateEqualTo(Date value) {
            addCriterion("ta_UpDate =", value, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateNotEqualTo(Date value) {
            addCriterion("ta_UpDate <>", value, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateGreaterThan(Date value) {
            addCriterion("ta_UpDate >", value, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("ta_UpDate >=", value, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateLessThan(Date value) {
            addCriterion("ta_UpDate <", value, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateLessThanOrEqualTo(Date value) {
            addCriterion("ta_UpDate <=", value, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateIn(List<Date> values) {
            addCriterion("ta_UpDate in", values, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateNotIn(List<Date> values) {
            addCriterion("ta_UpDate not in", values, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateBetween(Date value1, Date value2) {
            addCriterion("ta_UpDate between", value1, value2, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaUpdateNotBetween(Date value1, Date value2) {
            addCriterion("ta_UpDate not between", value1, value2, "taUpdate");
            return (Criteria) this;
        }

        public Criteria andTaDeleteIsNull() {
            addCriterion("ta_Delete is null");
            return (Criteria) this;
        }

        public Criteria andTaDeleteIsNotNull() {
            addCriterion("ta_Delete is not null");
            return (Criteria) this;
        }

        public Criteria andTaDeleteEqualTo(Boolean value) {
            addCriterion("ta_Delete =", value, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteNotEqualTo(Boolean value) {
            addCriterion("ta_Delete <>", value, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteGreaterThan(Boolean value) {
            addCriterion("ta_Delete >", value, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ta_Delete >=", value, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteLessThan(Boolean value) {
            addCriterion("ta_Delete <", value, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("ta_Delete <=", value, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteIn(List<Boolean> values) {
            addCriterion("ta_Delete in", values, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteNotIn(List<Boolean> values) {
            addCriterion("ta_Delete not in", values, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("ta_Delete between", value1, value2, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ta_Delete not between", value1, value2, "taDelete");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateIsNull() {
            addCriterion("ta_DeleteDate is null");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateIsNotNull() {
            addCriterion("ta_DeleteDate is not null");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateEqualTo(Date value) {
            addCriterion("ta_DeleteDate =", value, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateNotEqualTo(Date value) {
            addCriterion("ta_DeleteDate <>", value, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateGreaterThan(Date value) {
            addCriterion("ta_DeleteDate >", value, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateGreaterThanOrEqualTo(Date value) {
            addCriterion("ta_DeleteDate >=", value, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateLessThan(Date value) {
            addCriterion("ta_DeleteDate <", value, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateLessThanOrEqualTo(Date value) {
            addCriterion("ta_DeleteDate <=", value, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateIn(List<Date> values) {
            addCriterion("ta_DeleteDate in", values, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateNotIn(List<Date> values) {
            addCriterion("ta_DeleteDate not in", values, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateBetween(Date value1, Date value2) {
            addCriterion("ta_DeleteDate between", value1, value2, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeletedateNotBetween(Date value1, Date value2) {
            addCriterion("ta_DeleteDate not between", value1, value2, "taDeletedate");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserIsNull() {
            addCriterion("ta_DeleteUser is null");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserIsNotNull() {
            addCriterion("ta_DeleteUser is not null");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserEqualTo(Long value) {
            addCriterion("ta_DeleteUser =", value, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserNotEqualTo(Long value) {
            addCriterion("ta_DeleteUser <>", value, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserGreaterThan(Long value) {
            addCriterion("ta_DeleteUser >", value, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserGreaterThanOrEqualTo(Long value) {
            addCriterion("ta_DeleteUser >=", value, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserLessThan(Long value) {
            addCriterion("ta_DeleteUser <", value, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserLessThanOrEqualTo(Long value) {
            addCriterion("ta_DeleteUser <=", value, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserIn(List<Long> values) {
            addCriterion("ta_DeleteUser in", values, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserNotIn(List<Long> values) {
            addCriterion("ta_DeleteUser not in", values, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserBetween(Long value1, Long value2) {
            addCriterion("ta_DeleteUser between", value1, value2, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTaDeleteuserNotBetween(Long value1, Long value2) {
            addCriterion("ta_DeleteUser not between", value1, value2, "taDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriIsNull() {
            addCriterion("tal_LoaclURI is null");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriIsNotNull() {
            addCriterion("tal_LoaclURI is not null");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriEqualTo(String value) {
            addCriterion("tal_LoaclURI =", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriNotEqualTo(String value) {
            addCriterion("tal_LoaclURI <>", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriGreaterThan(String value) {
            addCriterion("tal_LoaclURI >", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriGreaterThanOrEqualTo(String value) {
            addCriterion("tal_LoaclURI >=", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriLessThan(String value) {
            addCriterion("tal_LoaclURI <", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriLessThanOrEqualTo(String value) {
            addCriterion("tal_LoaclURI <=", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriLike(String value) {
            addCriterion("tal_LoaclURI like", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriNotLike(String value) {
            addCriterion("tal_LoaclURI not like", value, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriIn(List<String> values) {
            addCriterion("tal_LoaclURI in", values, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriNotIn(List<String> values) {
            addCriterion("tal_LoaclURI not in", values, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriBetween(String value1, String value2) {
            addCriterion("tal_LoaclURI between", value1, value2, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTalLoacluriNotBetween(String value1, String value2) {
            addCriterion("tal_LoaclURI not between", value1, value2, "talLoacluri");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameIsNull() {
            addCriterion("ta_NewFaleName is null");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameIsNotNull() {
            addCriterion("ta_NewFaleName is not null");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameEqualTo(String value) {
            addCriterion("ta_NewFaleName =", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameNotEqualTo(String value) {
            addCriterion("ta_NewFaleName <>", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameGreaterThan(String value) {
            addCriterion("ta_NewFaleName >", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameGreaterThanOrEqualTo(String value) {
            addCriterion("ta_NewFaleName >=", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameLessThan(String value) {
            addCriterion("ta_NewFaleName <", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameLessThanOrEqualTo(String value) {
            addCriterion("ta_NewFaleName <=", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameLike(String value) {
            addCriterion("ta_NewFaleName like", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameNotLike(String value) {
            addCriterion("ta_NewFaleName not like", value, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameIn(List<String> values) {
            addCriterion("ta_NewFaleName in", values, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameNotIn(List<String> values) {
            addCriterion("ta_NewFaleName not in", values, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameBetween(String value1, String value2) {
            addCriterion("ta_NewFaleName between", value1, value2, "taNewfalename");
            return (Criteria) this;
        }

        public Criteria andTaNewfalenameNotBetween(String value1, String value2) {
            addCriterion("ta_NewFaleName not between", value1, value2, "taNewfalename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_attachment
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 04 15:43:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_attachment
     *
     * @mbg.generated Wed Dec 04 15:43:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}