package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClassDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public ClassDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTcIdIsNull() {
            addCriterion("tc_id is null");
            return (Criteria) this;
        }

        public Criteria andTcIdIsNotNull() {
            addCriterion("tc_id is not null");
            return (Criteria) this;
        }

        public Criteria andTcIdEqualTo(Long value) {
            addCriterion("tc_id =", value, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdNotEqualTo(Long value) {
            addCriterion("tc_id <>", value, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdGreaterThan(Long value) {
            addCriterion("tc_id >", value, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tc_id >=", value, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdLessThan(Long value) {
            addCriterion("tc_id <", value, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdLessThanOrEqualTo(Long value) {
            addCriterion("tc_id <=", value, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdIn(List<Long> values) {
            addCriterion("tc_id in", values, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdNotIn(List<Long> values) {
            addCriterion("tc_id not in", values, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdBetween(Long value1, Long value2) {
            addCriterion("tc_id between", value1, value2, "tcId");
            return (Criteria) this;
        }

        public Criteria andTcIdNotBetween(Long value1, Long value2) {
            addCriterion("tc_id not between", value1, value2, "tcId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNull() {
            addCriterion("major_ID is null");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNotNull() {
            addCriterion("major_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMajorIdEqualTo(Long value) {
            addCriterion("major_ID =", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotEqualTo(Long value) {
            addCriterion("major_ID <>", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThan(Long value) {
            addCriterion("major_ID >", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("major_ID >=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThan(Long value) {
            addCriterion("major_ID <", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThanOrEqualTo(Long value) {
            addCriterion("major_ID <=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIn(List<Long> values) {
            addCriterion("major_ID in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotIn(List<Long> values) {
            addCriterion("major_ID not in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdBetween(Long value1, Long value2) {
            addCriterion("major_ID between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotBetween(Long value1, Long value2) {
            addCriterion("major_ID not between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andClassCodeIsNull() {
            addCriterion("Class_Code is null");
            return (Criteria) this;
        }

        public Criteria andClassCodeIsNotNull() {
            addCriterion("Class_Code is not null");
            return (Criteria) this;
        }

        public Criteria andClassCodeEqualTo(String value) {
            addCriterion("Class_Code =", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotEqualTo(String value) {
            addCriterion("Class_Code <>", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeGreaterThan(String value) {
            addCriterion("Class_Code >", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Class_Code >=", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeLessThan(String value) {
            addCriterion("Class_Code <", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeLessThanOrEqualTo(String value) {
            addCriterion("Class_Code <=", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeLike(String value) {
            addCriterion("Class_Code like", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotLike(String value) {
            addCriterion("Class_Code not like", value, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeIn(List<String> values) {
            addCriterion("Class_Code in", values, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotIn(List<String> values) {
            addCriterion("Class_Code not in", values, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeBetween(String value1, String value2) {
            addCriterion("Class_Code between", value1, value2, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassCodeNotBetween(String value1, String value2) {
            addCriterion("Class_Code not between", value1, value2, "classCode");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_Name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_Name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_Name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_Name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_Name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_Name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_Name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_Name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_Name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_Name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_Name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_Name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_Name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_Name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeIsNull() {
            addCriterion("tc_CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeIsNotNull() {
            addCriterion("tc_CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeEqualTo(Date value) {
            addCriterion("tc_CreateTime =", value, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeNotEqualTo(Date value) {
            addCriterion("tc_CreateTime <>", value, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeGreaterThan(Date value) {
            addCriterion("tc_CreateTime >", value, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tc_CreateTime >=", value, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeLessThan(Date value) {
            addCriterion("tc_CreateTime <", value, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("tc_CreateTime <=", value, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeIn(List<Date> values) {
            addCriterion("tc_CreateTime in", values, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeNotIn(List<Date> values) {
            addCriterion("tc_CreateTime not in", values, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeBetween(Date value1, Date value2) {
            addCriterion("tc_CreateTime between", value1, value2, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("tc_CreateTime not between", value1, value2, "tcCreatetime");
            return (Criteria) this;
        }

        public Criteria andTcDeleteIsNull() {
            addCriterion("tc_Delete is null");
            return (Criteria) this;
        }

        public Criteria andTcDeleteIsNotNull() {
            addCriterion("tc_Delete is not null");
            return (Criteria) this;
        }

        public Criteria andTcDeleteEqualTo(Boolean value) {
            addCriterion("tc_Delete =", value, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteNotEqualTo(Boolean value) {
            addCriterion("tc_Delete <>", value, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteGreaterThan(Boolean value) {
            addCriterion("tc_Delete >", value, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tc_Delete >=", value, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteLessThan(Boolean value) {
            addCriterion("tc_Delete <", value, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("tc_Delete <=", value, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteIn(List<Boolean> values) {
            addCriterion("tc_Delete in", values, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteNotIn(List<Boolean> values) {
            addCriterion("tc_Delete not in", values, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("tc_Delete between", value1, value2, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tc_Delete not between", value1, value2, "tcDelete");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeIsNull() {
            addCriterion("tc_DeleteTime is null");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeIsNotNull() {
            addCriterion("tc_DeleteTime is not null");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeEqualTo(Date value) {
            addCriterion("tc_DeleteTime =", value, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeNotEqualTo(Date value) {
            addCriterion("tc_DeleteTime <>", value, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeGreaterThan(Date value) {
            addCriterion("tc_DeleteTime >", value, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tc_DeleteTime >=", value, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeLessThan(Date value) {
            addCriterion("tc_DeleteTime <", value, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeLessThanOrEqualTo(Date value) {
            addCriterion("tc_DeleteTime <=", value, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeIn(List<Date> values) {
            addCriterion("tc_DeleteTime in", values, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeNotIn(List<Date> values) {
            addCriterion("tc_DeleteTime not in", values, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeBetween(Date value1, Date value2) {
            addCriterion("tc_DeleteTime between", value1, value2, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeletetimeNotBetween(Date value1, Date value2) {
            addCriterion("tc_DeleteTime not between", value1, value2, "tcDeletetime");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserIsNull() {
            addCriterion("tc_DeleteUser is null");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserIsNotNull() {
            addCriterion("tc_DeleteUser is not null");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserEqualTo(String value) {
            addCriterion("tc_DeleteUser =", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserNotEqualTo(String value) {
            addCriterion("tc_DeleteUser <>", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserGreaterThan(String value) {
            addCriterion("tc_DeleteUser >", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserGreaterThanOrEqualTo(String value) {
            addCriterion("tc_DeleteUser >=", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserLessThan(String value) {
            addCriterion("tc_DeleteUser <", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserLessThanOrEqualTo(String value) {
            addCriterion("tc_DeleteUser <=", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserLike(String value) {
            addCriterion("tc_DeleteUser like", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserNotLike(String value) {
            addCriterion("tc_DeleteUser not like", value, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserIn(List<String> values) {
            addCriterion("tc_DeleteUser in", values, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserNotIn(List<String> values) {
            addCriterion("tc_DeleteUser not in", values, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserBetween(String value1, String value2) {
            addCriterion("tc_DeleteUser between", value1, value2, "tcDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTcDeleteuserNotBetween(String value1, String value2) {
            addCriterion("tc_DeleteUser not between", value1, value2, "tcDeleteuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 20 16:34:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_class
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}