package com.buoyantec.dataobject;

import java.util.Date;

public class enterpriseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.te_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Long teId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Name
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Code
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Addr
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_contact
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_ContacPhone
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epContacphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Site
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Email
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_REG_CAP
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epRegCap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_industry
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Nature
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.Approval_Status
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String approvalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Delete
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Boolean epDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_DeleteTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Date epDeletetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.DelectUser
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String delectuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise.ep_Introduction
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String epIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public enterpriseDO(Long teId, String epName, String epCode, String epAddr, String epContact, String epContacphone, String epSite, String epEmail, String epRegCap, String epIndustry, String epNature, String approvalStatus, Boolean epDelete, Date epDeletetime, String delectuser) {
        this.teId = teId;
        this.epName = epName;
        this.epCode = epCode;
        this.epAddr = epAddr;
        this.epContact = epContact;
        this.epContacphone = epContacphone;
        this.epSite = epSite;
        this.epEmail = epEmail;
        this.epRegCap = epRegCap;
        this.epIndustry = epIndustry;
        this.epNature = epNature;
        this.approvalStatus = approvalStatus;
        this.epDelete = epDelete;
        this.epDeletetime = epDeletetime;
        this.delectuser = delectuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public enterpriseDO(Long teId, String epName, String epCode, String epAddr, String epContact, String epContacphone, String epSite, String epEmail, String epRegCap, String epIndustry, String epNature, String approvalStatus, Boolean epDelete, Date epDeletetime, String delectuser, String epIntroduction) {
        this.teId = teId;
        this.epName = epName;
        this.epCode = epCode;
        this.epAddr = epAddr;
        this.epContact = epContact;
        this.epContacphone = epContacphone;
        this.epSite = epSite;
        this.epEmail = epEmail;
        this.epRegCap = epRegCap;
        this.epIndustry = epIndustry;
        this.epNature = epNature;
        this.approvalStatus = approvalStatus;
        this.epDelete = epDelete;
        this.epDeletetime = epDeletetime;
        this.delectuser = delectuser;
        this.epIntroduction = epIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public enterpriseDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.te_id
     *
     * @return the value of t_enterprise.te_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Long getTeId() {
        return teId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.te_id
     *
     * @param teId the value for t_enterprise.te_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTeId(Long teId) {
        this.teId = teId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Name
     *
     * @return the value of t_enterprise.ep_Name
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpName() {
        return epName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Name
     *
     * @param epName the value for t_enterprise.ep_Name
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpName(String epName) {
        this.epName = epName == null ? null : epName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Code
     *
     * @return the value of t_enterprise.ep_Code
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpCode() {
        return epCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Code
     *
     * @param epCode the value for t_enterprise.ep_Code
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpCode(String epCode) {
        this.epCode = epCode == null ? null : epCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Addr
     *
     * @return the value of t_enterprise.ep_Addr
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpAddr() {
        return epAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Addr
     *
     * @param epAddr the value for t_enterprise.ep_Addr
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpAddr(String epAddr) {
        this.epAddr = epAddr == null ? null : epAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_contact
     *
     * @return the value of t_enterprise.ep_contact
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpContact() {
        return epContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_contact
     *
     * @param epContact the value for t_enterprise.ep_contact
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpContact(String epContact) {
        this.epContact = epContact == null ? null : epContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_ContacPhone
     *
     * @return the value of t_enterprise.ep_ContacPhone
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpContacphone() {
        return epContacphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_ContacPhone
     *
     * @param epContacphone the value for t_enterprise.ep_ContacPhone
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpContacphone(String epContacphone) {
        this.epContacphone = epContacphone == null ? null : epContacphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Site
     *
     * @return the value of t_enterprise.ep_Site
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpSite() {
        return epSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Site
     *
     * @param epSite the value for t_enterprise.ep_Site
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpSite(String epSite) {
        this.epSite = epSite == null ? null : epSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Email
     *
     * @return the value of t_enterprise.ep_Email
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpEmail() {
        return epEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Email
     *
     * @param epEmail the value for t_enterprise.ep_Email
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpEmail(String epEmail) {
        this.epEmail = epEmail == null ? null : epEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_REG_CAP
     *
     * @return the value of t_enterprise.ep_REG_CAP
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpRegCap() {
        return epRegCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_REG_CAP
     *
     * @param epRegCap the value for t_enterprise.ep_REG_CAP
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpRegCap(String epRegCap) {
        this.epRegCap = epRegCap == null ? null : epRegCap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_industry
     *
     * @return the value of t_enterprise.ep_industry
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpIndustry() {
        return epIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_industry
     *
     * @param epIndustry the value for t_enterprise.ep_industry
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpIndustry(String epIndustry) {
        this.epIndustry = epIndustry == null ? null : epIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Nature
     *
     * @return the value of t_enterprise.ep_Nature
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpNature() {
        return epNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Nature
     *
     * @param epNature the value for t_enterprise.ep_Nature
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpNature(String epNature) {
        this.epNature = epNature == null ? null : epNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.Approval_Status
     *
     * @return the value of t_enterprise.Approval_Status
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.Approval_Status
     *
     * @param approvalStatus the value for t_enterprise.Approval_Status
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Delete
     *
     * @return the value of t_enterprise.ep_Delete
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Boolean getEpDelete() {
        return epDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Delete
     *
     * @param epDelete the value for t_enterprise.ep_Delete
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpDelete(Boolean epDelete) {
        this.epDelete = epDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_DeleteTime
     *
     * @return the value of t_enterprise.ep_DeleteTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Date getEpDeletetime() {
        return epDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_DeleteTime
     *
     * @param epDeletetime the value for t_enterprise.ep_DeleteTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpDeletetime(Date epDeletetime) {
        this.epDeletetime = epDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.DelectUser
     *
     * @return the value of t_enterprise.DelectUser
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getDelectuser() {
        return delectuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.DelectUser
     *
     * @param delectuser the value for t_enterprise.DelectUser
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setDelectuser(String delectuser) {
        this.delectuser = delectuser == null ? null : delectuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise.ep_Introduction
     *
     * @return the value of t_enterprise.ep_Introduction
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getEpIntroduction() {
        return epIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise.ep_Introduction
     *
     * @param epIntroduction the value for t_enterprise.ep_Introduction
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpIntroduction(String epIntroduction) {
        this.epIntroduction = epIntroduction == null ? null : epIntroduction.trim();
    }
}