package com.buoyantec.dataobject;

import java.util.Date;

public class news_classDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Long tncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_Name
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private String tncName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_ICO
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private String tncIco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc__DID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Long tncDid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_CarteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Date tncCartetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_modifTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Date tncModiftime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_ModifUserID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Long tncModifuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tbc_Delete
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Boolean tbcDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tu_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Long tuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_DeleteUserID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Long tncDeleteuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_class.tnc_DeleteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Date tncDeletetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public news_classDO(Long tncId, String tncName, String tncIco, Long tncDid, Date tncCartetime, Date tncModiftime, Long tncModifuserid, Boolean tbcDelete, Long tuId, Long tncDeleteuserid, Date tncDeletetime) {
        this.tncId = tncId;
        this.tncName = tncName;
        this.tncIco = tncIco;
        this.tncDid = tncDid;
        this.tncCartetime = tncCartetime;
        this.tncModiftime = tncModiftime;
        this.tncModifuserid = tncModifuserid;
        this.tbcDelete = tbcDelete;
        this.tuId = tuId;
        this.tncDeleteuserid = tncDeleteuserid;
        this.tncDeletetime = tncDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_class
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public news_classDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_id
     *
     * @return the value of t_news_class.tnc_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Long getTncId() {
        return tncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_id
     *
     * @param tncId the value for t_news_class.tnc_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncId(Long tncId) {
        this.tncId = tncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_Name
     *
     * @return the value of t_news_class.tnc_Name
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public String getTncName() {
        return tncName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_Name
     *
     * @param tncName the value for t_news_class.tnc_Name
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncName(String tncName) {
        this.tncName = tncName == null ? null : tncName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_ICO
     *
     * @return the value of t_news_class.tnc_ICO
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public String getTncIco() {
        return tncIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_ICO
     *
     * @param tncIco the value for t_news_class.tnc_ICO
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncIco(String tncIco) {
        this.tncIco = tncIco == null ? null : tncIco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc__DID
     *
     * @return the value of t_news_class.tnc__DID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Long getTncDid() {
        return tncDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc__DID
     *
     * @param tncDid the value for t_news_class.tnc__DID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncDid(Long tncDid) {
        this.tncDid = tncDid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_CarteTime
     *
     * @return the value of t_news_class.tnc_CarteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Date getTncCartetime() {
        return tncCartetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_CarteTime
     *
     * @param tncCartetime the value for t_news_class.tnc_CarteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncCartetime(Date tncCartetime) {
        this.tncCartetime = tncCartetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_modifTime
     *
     * @return the value of t_news_class.tnc_modifTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Date getTncModiftime() {
        return tncModiftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_modifTime
     *
     * @param tncModiftime the value for t_news_class.tnc_modifTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncModiftime(Date tncModiftime) {
        this.tncModiftime = tncModiftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_ModifUserID
     *
     * @return the value of t_news_class.tnc_ModifUserID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Long getTncModifuserid() {
        return tncModifuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_ModifUserID
     *
     * @param tncModifuserid the value for t_news_class.tnc_ModifUserID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncModifuserid(Long tncModifuserid) {
        this.tncModifuserid = tncModifuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tbc_Delete
     *
     * @return the value of t_news_class.tbc_Delete
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Boolean getTbcDelete() {
        return tbcDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tbc_Delete
     *
     * @param tbcDelete the value for t_news_class.tbc_Delete
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTbcDelete(Boolean tbcDelete) {
        this.tbcDelete = tbcDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tu_id
     *
     * @return the value of t_news_class.tu_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Long getTuId() {
        return tuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tu_id
     *
     * @param tuId the value for t_news_class.tu_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTuId(Long tuId) {
        this.tuId = tuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_DeleteUserID
     *
     * @return the value of t_news_class.tnc_DeleteUserID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Long getTncDeleteuserid() {
        return tncDeleteuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_DeleteUserID
     *
     * @param tncDeleteuserid the value for t_news_class.tnc_DeleteUserID
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncDeleteuserid(Long tncDeleteuserid) {
        this.tncDeleteuserid = tncDeleteuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_class.tnc_DeleteTime
     *
     * @return the value of t_news_class.tnc_DeleteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Date getTncDeletetime() {
        return tncDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_class.tnc_DeleteTime
     *
     * @param tncDeletetime the value for t_news_class.tnc_DeleteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTncDeletetime(Date tncDeletetime) {
        this.tncDeletetime = tncDeletetime;
    }
}