package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class newsDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public newsDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTnIdIsNull() {
            addCriterion("tn_ID is null");
            return (Criteria) this;
        }

        public Criteria andTnIdIsNotNull() {
            addCriterion("tn_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTnIdEqualTo(Long value) {
            addCriterion("tn_ID =", value, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdNotEqualTo(Long value) {
            addCriterion("tn_ID <>", value, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdGreaterThan(Long value) {
            addCriterion("tn_ID >", value, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tn_ID >=", value, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdLessThan(Long value) {
            addCriterion("tn_ID <", value, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdLessThanOrEqualTo(Long value) {
            addCriterion("tn_ID <=", value, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdIn(List<Long> values) {
            addCriterion("tn_ID in", values, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdNotIn(List<Long> values) {
            addCriterion("tn_ID not in", values, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdBetween(Long value1, Long value2) {
            addCriterion("tn_ID between", value1, value2, "tnId");
            return (Criteria) this;
        }

        public Criteria andTnIdNotBetween(Long value1, Long value2) {
            addCriterion("tn_ID not between", value1, value2, "tnId");
            return (Criteria) this;
        }

        public Criteria andTuIdIsNull() {
            addCriterion("tu_id is null");
            return (Criteria) this;
        }

        public Criteria andTuIdIsNotNull() {
            addCriterion("tu_id is not null");
            return (Criteria) this;
        }

        public Criteria andTuIdEqualTo(Long value) {
            addCriterion("tu_id =", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdNotEqualTo(Long value) {
            addCriterion("tu_id <>", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdGreaterThan(Long value) {
            addCriterion("tu_id >", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tu_id >=", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdLessThan(Long value) {
            addCriterion("tu_id <", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdLessThanOrEqualTo(Long value) {
            addCriterion("tu_id <=", value, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdIn(List<Long> values) {
            addCriterion("tu_id in", values, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdNotIn(List<Long> values) {
            addCriterion("tu_id not in", values, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdBetween(Long value1, Long value2) {
            addCriterion("tu_id between", value1, value2, "tuId");
            return (Criteria) this;
        }

        public Criteria andTuIdNotBetween(Long value1, Long value2) {
            addCriterion("tu_id not between", value1, value2, "tuId");
            return (Criteria) this;
        }

        public Criteria andTncIdIsNull() {
            addCriterion("tnc_ID is null");
            return (Criteria) this;
        }

        public Criteria andTncIdIsNotNull() {
            addCriterion("tnc_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTncIdEqualTo(Long value) {
            addCriterion("tnc_ID =", value, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdNotEqualTo(Long value) {
            addCriterion("tnc_ID <>", value, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdGreaterThan(Long value) {
            addCriterion("tnc_ID >", value, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tnc_ID >=", value, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdLessThan(Long value) {
            addCriterion("tnc_ID <", value, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdLessThanOrEqualTo(Long value) {
            addCriterion("tnc_ID <=", value, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdIn(List<Long> values) {
            addCriterion("tnc_ID in", values, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdNotIn(List<Long> values) {
            addCriterion("tnc_ID not in", values, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdBetween(Long value1, Long value2) {
            addCriterion("tnc_ID between", value1, value2, "tncId");
            return (Criteria) this;
        }

        public Criteria andTncIdNotBetween(Long value1, Long value2) {
            addCriterion("tnc_ID not between", value1, value2, "tncId");
            return (Criteria) this;
        }

        public Criteria andTnTitleIsNull() {
            addCriterion("tn_Title is null");
            return (Criteria) this;
        }

        public Criteria andTnTitleIsNotNull() {
            addCriterion("tn_Title is not null");
            return (Criteria) this;
        }

        public Criteria andTnTitleEqualTo(String value) {
            addCriterion("tn_Title =", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleNotEqualTo(String value) {
            addCriterion("tn_Title <>", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleGreaterThan(String value) {
            addCriterion("tn_Title >", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleGreaterThanOrEqualTo(String value) {
            addCriterion("tn_Title >=", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleLessThan(String value) {
            addCriterion("tn_Title <", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleLessThanOrEqualTo(String value) {
            addCriterion("tn_Title <=", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleLike(String value) {
            addCriterion("tn_Title like", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleNotLike(String value) {
            addCriterion("tn_Title not like", value, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleIn(List<String> values) {
            addCriterion("tn_Title in", values, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleNotIn(List<String> values) {
            addCriterion("tn_Title not in", values, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleBetween(String value1, String value2) {
            addCriterion("tn_Title between", value1, value2, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnTitleNotBetween(String value1, String value2) {
            addCriterion("tn_Title not between", value1, value2, "tnTitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleIsNull() {
            addCriterion("tn_ViceTitle is null");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleIsNotNull() {
            addCriterion("tn_ViceTitle is not null");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleEqualTo(String value) {
            addCriterion("tn_ViceTitle =", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleNotEqualTo(String value) {
            addCriterion("tn_ViceTitle <>", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleGreaterThan(String value) {
            addCriterion("tn_ViceTitle >", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleGreaterThanOrEqualTo(String value) {
            addCriterion("tn_ViceTitle >=", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleLessThan(String value) {
            addCriterion("tn_ViceTitle <", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleLessThanOrEqualTo(String value) {
            addCriterion("tn_ViceTitle <=", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleLike(String value) {
            addCriterion("tn_ViceTitle like", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleNotLike(String value) {
            addCriterion("tn_ViceTitle not like", value, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleIn(List<String> values) {
            addCriterion("tn_ViceTitle in", values, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleNotIn(List<String> values) {
            addCriterion("tn_ViceTitle not in", values, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleBetween(String value1, String value2) {
            addCriterion("tn_ViceTitle between", value1, value2, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnVicetitleNotBetween(String value1, String value2) {
            addCriterion("tn_ViceTitle not between", value1, value2, "tnVicetitle");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleIsNull() {
            addCriterion("tn_TitleCole is null");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleIsNotNull() {
            addCriterion("tn_TitleCole is not null");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleEqualTo(String value) {
            addCriterion("tn_TitleCole =", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleNotEqualTo(String value) {
            addCriterion("tn_TitleCole <>", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleGreaterThan(String value) {
            addCriterion("tn_TitleCole >", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleGreaterThanOrEqualTo(String value) {
            addCriterion("tn_TitleCole >=", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleLessThan(String value) {
            addCriterion("tn_TitleCole <", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleLessThanOrEqualTo(String value) {
            addCriterion("tn_TitleCole <=", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleLike(String value) {
            addCriterion("tn_TitleCole like", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleNotLike(String value) {
            addCriterion("tn_TitleCole not like", value, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleIn(List<String> values) {
            addCriterion("tn_TitleCole in", values, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleNotIn(List<String> values) {
            addCriterion("tn_TitleCole not in", values, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleBetween(String value1, String value2) {
            addCriterion("tn_TitleCole between", value1, value2, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlecoleNotBetween(String value1, String value2) {
            addCriterion("tn_TitleCole not between", value1, value2, "tnTitlecole");
            return (Criteria) this;
        }

        public Criteria andTnTitlebIsNull() {
            addCriterion("tn_TitleB is null");
            return (Criteria) this;
        }

        public Criteria andTnTitlebIsNotNull() {
            addCriterion("tn_TitleB is not null");
            return (Criteria) this;
        }

        public Criteria andTnTitlebEqualTo(Integer value) {
            addCriterion("tn_TitleB =", value, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebNotEqualTo(Integer value) {
            addCriterion("tn_TitleB <>", value, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebGreaterThan(Integer value) {
            addCriterion("tn_TitleB >", value, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebGreaterThanOrEqualTo(Integer value) {
            addCriterion("tn_TitleB >=", value, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebLessThan(Integer value) {
            addCriterion("tn_TitleB <", value, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebLessThanOrEqualTo(Integer value) {
            addCriterion("tn_TitleB <=", value, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebIn(List<Integer> values) {
            addCriterion("tn_TitleB in", values, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebNotIn(List<Integer> values) {
            addCriterion("tn_TitleB not in", values, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebBetween(Integer value1, Integer value2) {
            addCriterion("tn_TitleB between", value1, value2, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnTitlebNotBetween(Integer value1, Integer value2) {
            addCriterion("tn_TitleB not between", value1, value2, "tnTitleb");
            return (Criteria) this;
        }

        public Criteria andTnOrdeIsNull() {
            addCriterion("tn_Orde is null");
            return (Criteria) this;
        }

        public Criteria andTnOrdeIsNotNull() {
            addCriterion("tn_Orde is not null");
            return (Criteria) this;
        }

        public Criteria andTnOrdeEqualTo(Integer value) {
            addCriterion("tn_Orde =", value, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeNotEqualTo(Integer value) {
            addCriterion("tn_Orde <>", value, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeGreaterThan(Integer value) {
            addCriterion("tn_Orde >", value, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tn_Orde >=", value, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeLessThan(Integer value) {
            addCriterion("tn_Orde <", value, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeLessThanOrEqualTo(Integer value) {
            addCriterion("tn_Orde <=", value, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeIn(List<Integer> values) {
            addCriterion("tn_Orde in", values, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeNotIn(List<Integer> values) {
            addCriterion("tn_Orde not in", values, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeBetween(Integer value1, Integer value2) {
            addCriterion("tn_Orde between", value1, value2, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnOrdeNotBetween(Integer value1, Integer value2) {
            addCriterion("tn_Orde not between", value1, value2, "tnOrde");
            return (Criteria) this;
        }

        public Criteria andTnIntrIsNull() {
            addCriterion("tn_intr is null");
            return (Criteria) this;
        }

        public Criteria andTnIntrIsNotNull() {
            addCriterion("tn_intr is not null");
            return (Criteria) this;
        }

        public Criteria andTnIntrEqualTo(String value) {
            addCriterion("tn_intr =", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrNotEqualTo(String value) {
            addCriterion("tn_intr <>", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrGreaterThan(String value) {
            addCriterion("tn_intr >", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrGreaterThanOrEqualTo(String value) {
            addCriterion("tn_intr >=", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrLessThan(String value) {
            addCriterion("tn_intr <", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrLessThanOrEqualTo(String value) {
            addCriterion("tn_intr <=", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrLike(String value) {
            addCriterion("tn_intr like", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrNotLike(String value) {
            addCriterion("tn_intr not like", value, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrIn(List<String> values) {
            addCriterion("tn_intr in", values, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrNotIn(List<String> values) {
            addCriterion("tn_intr not in", values, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrBetween(String value1, String value2) {
            addCriterion("tn_intr between", value1, value2, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnIntrNotBetween(String value1, String value2) {
            addCriterion("tn_intr not between", value1, value2, "tnIntr");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcIsNull() {
            addCriterion("tn_number_OC is null");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcIsNotNull() {
            addCriterion("tn_number_OC is not null");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcEqualTo(Integer value) {
            addCriterion("tn_number_OC =", value, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcNotEqualTo(Integer value) {
            addCriterion("tn_number_OC <>", value, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcGreaterThan(Integer value) {
            addCriterion("tn_number_OC >", value, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcGreaterThanOrEqualTo(Integer value) {
            addCriterion("tn_number_OC >=", value, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcLessThan(Integer value) {
            addCriterion("tn_number_OC <", value, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcLessThanOrEqualTo(Integer value) {
            addCriterion("tn_number_OC <=", value, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcIn(List<Integer> values) {
            addCriterion("tn_number_OC in", values, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcNotIn(List<Integer> values) {
            addCriterion("tn_number_OC not in", values, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcBetween(Integer value1, Integer value2) {
            addCriterion("tn_number_OC between", value1, value2, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnNumberOcNotBetween(Integer value1, Integer value2) {
            addCriterion("tn_number_OC not between", value1, value2, "tnNumberOc");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeIsNull() {
            addCriterion("tn_releaseDatetime is null");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeIsNotNull() {
            addCriterion("tn_releaseDatetime is not null");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeEqualTo(Date value) {
            addCriterion("tn_releaseDatetime =", value, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeNotEqualTo(Date value) {
            addCriterion("tn_releaseDatetime <>", value, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeGreaterThan(Date value) {
            addCriterion("tn_releaseDatetime >", value, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tn_releaseDatetime >=", value, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeLessThan(Date value) {
            addCriterion("tn_releaseDatetime <", value, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeLessThanOrEqualTo(Date value) {
            addCriterion("tn_releaseDatetime <=", value, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeIn(List<Date> values) {
            addCriterion("tn_releaseDatetime in", values, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeNotIn(List<Date> values) {
            addCriterion("tn_releaseDatetime not in", values, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeBetween(Date value1, Date value2) {
            addCriterion("tn_releaseDatetime between", value1, value2, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnReleasedatetimeNotBetween(Date value1, Date value2) {
            addCriterion("tn_releaseDatetime not between", value1, value2, "tnReleasedatetime");
            return (Criteria) this;
        }

        public Criteria andTnAuthorIsNull() {
            addCriterion("tn_Author is null");
            return (Criteria) this;
        }

        public Criteria andTnAuthorIsNotNull() {
            addCriterion("tn_Author is not null");
            return (Criteria) this;
        }

        public Criteria andTnAuthorEqualTo(String value) {
            addCriterion("tn_Author =", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorNotEqualTo(String value) {
            addCriterion("tn_Author <>", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorGreaterThan(String value) {
            addCriterion("tn_Author >", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("tn_Author >=", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorLessThan(String value) {
            addCriterion("tn_Author <", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorLessThanOrEqualTo(String value) {
            addCriterion("tn_Author <=", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorLike(String value) {
            addCriterion("tn_Author like", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorNotLike(String value) {
            addCriterion("tn_Author not like", value, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorIn(List<String> values) {
            addCriterion("tn_Author in", values, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorNotIn(List<String> values) {
            addCriterion("tn_Author not in", values, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorBetween(String value1, String value2) {
            addCriterion("tn_Author between", value1, value2, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnAuthorNotBetween(String value1, String value2) {
            addCriterion("tn_Author not between", value1, value2, "tnAuthor");
            return (Criteria) this;
        }

        public Criteria andTnCoverIsNull() {
            addCriterion("tn_Cover is null");
            return (Criteria) this;
        }

        public Criteria andTnCoverIsNotNull() {
            addCriterion("tn_Cover is not null");
            return (Criteria) this;
        }

        public Criteria andTnCoverEqualTo(String value) {
            addCriterion("tn_Cover =", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverNotEqualTo(String value) {
            addCriterion("tn_Cover <>", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverGreaterThan(String value) {
            addCriterion("tn_Cover >", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverGreaterThanOrEqualTo(String value) {
            addCriterion("tn_Cover >=", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverLessThan(String value) {
            addCriterion("tn_Cover <", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverLessThanOrEqualTo(String value) {
            addCriterion("tn_Cover <=", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverLike(String value) {
            addCriterion("tn_Cover like", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverNotLike(String value) {
            addCriterion("tn_Cover not like", value, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverIn(List<String> values) {
            addCriterion("tn_Cover in", values, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverNotIn(List<String> values) {
            addCriterion("tn_Cover not in", values, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverBetween(String value1, String value2) {
            addCriterion("tn_Cover between", value1, value2, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCoverNotBetween(String value1, String value2) {
            addCriterion("tn_Cover not between", value1, value2, "tnCover");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeIsNull() {
            addCriterion("tn_CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeIsNotNull() {
            addCriterion("tn_CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeEqualTo(Date value) {
            addCriterion("tn_CreateTime =", value, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeNotEqualTo(Date value) {
            addCriterion("tn_CreateTime <>", value, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeGreaterThan(Date value) {
            addCriterion("tn_CreateTime >", value, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tn_CreateTime >=", value, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeLessThan(Date value) {
            addCriterion("tn_CreateTime <", value, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("tn_CreateTime <=", value, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeIn(List<Date> values) {
            addCriterion("tn_CreateTime in", values, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeNotIn(List<Date> values) {
            addCriterion("tn_CreateTime not in", values, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeBetween(Date value1, Date value2) {
            addCriterion("tn_CreateTime between", value1, value2, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("tn_CreateTime not between", value1, value2, "tnCreatetime");
            return (Criteria) this;
        }

        public Criteria andTnDeleteIsNull() {
            addCriterion("tn_delete is null");
            return (Criteria) this;
        }

        public Criteria andTnDeleteIsNotNull() {
            addCriterion("tn_delete is not null");
            return (Criteria) this;
        }

        public Criteria andTnDeleteEqualTo(Boolean value) {
            addCriterion("tn_delete =", value, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteNotEqualTo(Boolean value) {
            addCriterion("tn_delete <>", value, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteGreaterThan(Boolean value) {
            addCriterion("tn_delete >", value, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tn_delete >=", value, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteLessThan(Boolean value) {
            addCriterion("tn_delete <", value, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("tn_delete <=", value, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteIn(List<Boolean> values) {
            addCriterion("tn_delete in", values, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteNotIn(List<Boolean> values) {
            addCriterion("tn_delete not in", values, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("tn_delete between", value1, value2, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tn_delete not between", value1, value2, "tnDelete");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserIsNull() {
            addCriterion("tn_midefUser is null");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserIsNotNull() {
            addCriterion("tn_midefUser is not null");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserEqualTo(Long value) {
            addCriterion("tn_midefUser =", value, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserNotEqualTo(Long value) {
            addCriterion("tn_midefUser <>", value, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserGreaterThan(Long value) {
            addCriterion("tn_midefUser >", value, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserGreaterThanOrEqualTo(Long value) {
            addCriterion("tn_midefUser >=", value, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserLessThan(Long value) {
            addCriterion("tn_midefUser <", value, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserLessThanOrEqualTo(Long value) {
            addCriterion("tn_midefUser <=", value, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserIn(List<Long> values) {
            addCriterion("tn_midefUser in", values, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserNotIn(List<Long> values) {
            addCriterion("tn_midefUser not in", values, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserBetween(Long value1, Long value2) {
            addCriterion("tn_midefUser between", value1, value2, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMidefuserNotBetween(Long value1, Long value2) {
            addCriterion("tn_midefUser not between", value1, value2, "tnMidefuser");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeIsNull() {
            addCriterion("tn_midefTime is null");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeIsNotNull() {
            addCriterion("tn_midefTime is not null");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeEqualTo(Date value) {
            addCriterion("tn_midefTime =", value, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeNotEqualTo(Date value) {
            addCriterion("tn_midefTime <>", value, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeGreaterThan(Date value) {
            addCriterion("tn_midefTime >", value, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tn_midefTime >=", value, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeLessThan(Date value) {
            addCriterion("tn_midefTime <", value, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeLessThanOrEqualTo(Date value) {
            addCriterion("tn_midefTime <=", value, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeIn(List<Date> values) {
            addCriterion("tn_midefTime in", values, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeNotIn(List<Date> values) {
            addCriterion("tn_midefTime not in", values, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeBetween(Date value1, Date value2) {
            addCriterion("tn_midefTime between", value1, value2, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnMideftimeNotBetween(Date value1, Date value2) {
            addCriterion("tn_midefTime not between", value1, value2, "tnMideftime");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserIsNull() {
            addCriterion("tn_DeleteUser is null");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserIsNotNull() {
            addCriterion("tn_DeleteUser is not null");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserEqualTo(Long value) {
            addCriterion("tn_DeleteUser =", value, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserNotEqualTo(Long value) {
            addCriterion("tn_DeleteUser <>", value, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserGreaterThan(Long value) {
            addCriterion("tn_DeleteUser >", value, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserGreaterThanOrEqualTo(Long value) {
            addCriterion("tn_DeleteUser >=", value, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserLessThan(Long value) {
            addCriterion("tn_DeleteUser <", value, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserLessThanOrEqualTo(Long value) {
            addCriterion("tn_DeleteUser <=", value, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserIn(List<Long> values) {
            addCriterion("tn_DeleteUser in", values, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserNotIn(List<Long> values) {
            addCriterion("tn_DeleteUser not in", values, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserBetween(Long value1, Long value2) {
            addCriterion("tn_DeleteUser between", value1, value2, "tnDeleteuser");
            return (Criteria) this;
        }

        public Criteria andTnDeleteuserNotBetween(Long value1, Long value2) {
            addCriterion("tn_DeleteUser not between", value1, value2, "tnDeleteuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_news
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 25 10:09:14 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_news
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}