package com.buoyantec.dataobject;

import java.util.Date;

public class rightDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.tr_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Long trId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.parent_tr_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Long parentTrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.right_name
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String rightName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.description
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.ep_Delete
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Boolean epDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.tr_CreateTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Date trCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.ep_DeleteTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Date epDeletetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_right.DelectUser
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String delectuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public rightDO(Long trId, Long parentTrId, String rightName, String description, Boolean epDelete, Date trCreatetime, Date epDeletetime, String delectuser) {
        this.trId = trId;
        this.parentTrId = parentTrId;
        this.rightName = rightName;
        this.description = description;
        this.epDelete = epDelete;
        this.trCreatetime = trCreatetime;
        this.epDeletetime = epDeletetime;
        this.delectuser = delectuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_right
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public rightDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.tr_id
     *
     * @return the value of t_right.tr_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Long getTrId() {
        return trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.tr_id
     *
     * @param trId the value for t_right.tr_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTrId(Long trId) {
        this.trId = trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.parent_tr_id
     *
     * @return the value of t_right.parent_tr_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Long getParentTrId() {
        return parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.parent_tr_id
     *
     * @param parentTrId the value for t_right.parent_tr_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setParentTrId(Long parentTrId) {
        this.parentTrId = parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.right_name
     *
     * @return the value of t_right.right_name
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.right_name
     *
     * @param rightName the value for t_right.right_name
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.description
     *
     * @return the value of t_right.description
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.description
     *
     * @param description the value for t_right.description
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.ep_Delete
     *
     * @return the value of t_right.ep_Delete
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Boolean getEpDelete() {
        return epDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.ep_Delete
     *
     * @param epDelete the value for t_right.ep_Delete
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpDelete(Boolean epDelete) {
        this.epDelete = epDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.tr_CreateTime
     *
     * @return the value of t_right.tr_CreateTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Date getTrCreatetime() {
        return trCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.tr_CreateTime
     *
     * @param trCreatetime the value for t_right.tr_CreateTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTrCreatetime(Date trCreatetime) {
        this.trCreatetime = trCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.ep_DeleteTime
     *
     * @return the value of t_right.ep_DeleteTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Date getEpDeletetime() {
        return epDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.ep_DeleteTime
     *
     * @param epDeletetime the value for t_right.ep_DeleteTime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setEpDeletetime(Date epDeletetime) {
        this.epDeletetime = epDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_right.DelectUser
     *
     * @return the value of t_right.DelectUser
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getDelectuser() {
        return delectuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_right.DelectUser
     *
     * @param delectuser the value for t_right.DelectUser
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setDelectuser(String delectuser) {
        this.delectuser = delectuser == null ? null : delectuser.trim();
    }
}