package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class rolerightrelationDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public rolerightrelationDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTrrIdIsNull() {
            addCriterion("trr_id is null");
            return (Criteria) this;
        }

        public Criteria andTrrIdIsNotNull() {
            addCriterion("trr_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrrIdEqualTo(Long value) {
            addCriterion("trr_id =", value, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdNotEqualTo(Long value) {
            addCriterion("trr_id <>", value, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdGreaterThan(Long value) {
            addCriterion("trr_id >", value, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("trr_id >=", value, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdLessThan(Long value) {
            addCriterion("trr_id <", value, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdLessThanOrEqualTo(Long value) {
            addCriterion("trr_id <=", value, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdIn(List<Long> values) {
            addCriterion("trr_id in", values, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdNotIn(List<Long> values) {
            addCriterion("trr_id not in", values, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdBetween(Long value1, Long value2) {
            addCriterion("trr_id between", value1, value2, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrrIdNotBetween(Long value1, Long value2) {
            addCriterion("trr_id not between", value1, value2, "trrId");
            return (Criteria) this;
        }

        public Criteria andTrIdIsNull() {
            addCriterion("tr_id is null");
            return (Criteria) this;
        }

        public Criteria andTrIdIsNotNull() {
            addCriterion("tr_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrIdEqualTo(Long value) {
            addCriterion("tr_id =", value, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdNotEqualTo(Long value) {
            addCriterion("tr_id <>", value, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdGreaterThan(Long value) {
            addCriterion("tr_id >", value, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tr_id >=", value, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdLessThan(Long value) {
            addCriterion("tr_id <", value, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdLessThanOrEqualTo(Long value) {
            addCriterion("tr_id <=", value, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdIn(List<Long> values) {
            addCriterion("tr_id in", values, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdNotIn(List<Long> values) {
            addCriterion("tr_id not in", values, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdBetween(Long value1, Long value2) {
            addCriterion("tr_id between", value1, value2, "trId");
            return (Criteria) this;
        }

        public Criteria andTrIdNotBetween(Long value1, Long value2) {
            addCriterion("tr_id not between", value1, value2, "trId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdIsNull() {
            addCriterion("T_R_tr_id is null");
            return (Criteria) this;
        }

        public Criteria andTRTrIdIsNotNull() {
            addCriterion("T_R_tr_id is not null");
            return (Criteria) this;
        }

        public Criteria andTRTrIdEqualTo(Long value) {
            addCriterion("T_R_tr_id =", value, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdNotEqualTo(Long value) {
            addCriterion("T_R_tr_id <>", value, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdGreaterThan(Long value) {
            addCriterion("T_R_tr_id >", value, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("T_R_tr_id >=", value, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdLessThan(Long value) {
            addCriterion("T_R_tr_id <", value, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdLessThanOrEqualTo(Long value) {
            addCriterion("T_R_tr_id <=", value, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdIn(List<Long> values) {
            addCriterion("T_R_tr_id in", values, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdNotIn(List<Long> values) {
            addCriterion("T_R_tr_id not in", values, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdBetween(Long value1, Long value2) {
            addCriterion("T_R_tr_id between", value1, value2, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andTRTrIdNotBetween(Long value1, Long value2) {
            addCriterion("T_R_tr_id not between", value1, value2, "tRTrId");
            return (Criteria) this;
        }

        public Criteria andRightTypeIsNull() {
            addCriterion("right_type is null");
            return (Criteria) this;
        }

        public Criteria andRightTypeIsNotNull() {
            addCriterion("right_type is not null");
            return (Criteria) this;
        }

        public Criteria andRightTypeEqualTo(Integer value) {
            addCriterion("right_type =", value, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeNotEqualTo(Integer value) {
            addCriterion("right_type <>", value, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeGreaterThan(Integer value) {
            addCriterion("right_type >", value, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("right_type >=", value, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeLessThan(Integer value) {
            addCriterion("right_type <", value, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeLessThanOrEqualTo(Integer value) {
            addCriterion("right_type <=", value, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeIn(List<Integer> values) {
            addCriterion("right_type in", values, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeNotIn(List<Integer> values) {
            addCriterion("right_type not in", values, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeBetween(Integer value1, Integer value2) {
            addCriterion("right_type between", value1, value2, "rightType");
            return (Criteria) this;
        }

        public Criteria andRightTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("right_type not between", value1, value2, "rightType");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeIsNull() {
            addCriterion("trr_CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeIsNotNull() {
            addCriterion("trr_CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeEqualTo(Date value) {
            addCriterion("trr_CreateTime =", value, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeNotEqualTo(Date value) {
            addCriterion("trr_CreateTime <>", value, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeGreaterThan(Date value) {
            addCriterion("trr_CreateTime >", value, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("trr_CreateTime >=", value, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeLessThan(Date value) {
            addCriterion("trr_CreateTime <", value, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("trr_CreateTime <=", value, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeIn(List<Date> values) {
            addCriterion("trr_CreateTime in", values, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeNotIn(List<Date> values) {
            addCriterion("trr_CreateTime not in", values, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeBetween(Date value1, Date value2) {
            addCriterion("trr_CreateTime between", value1, value2, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andTrrCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("trr_CreateTime not between", value1, value2, "trrCreatetime");
            return (Criteria) this;
        }

        public Criteria andEpDeleteIsNull() {
            addCriterion("ep_Delete is null");
            return (Criteria) this;
        }

        public Criteria andEpDeleteIsNotNull() {
            addCriterion("ep_Delete is not null");
            return (Criteria) this;
        }

        public Criteria andEpDeleteEqualTo(Boolean value) {
            addCriterion("ep_Delete =", value, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteNotEqualTo(Boolean value) {
            addCriterion("ep_Delete <>", value, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteGreaterThan(Boolean value) {
            addCriterion("ep_Delete >", value, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ep_Delete >=", value, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteLessThan(Boolean value) {
            addCriterion("ep_Delete <", value, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("ep_Delete <=", value, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteIn(List<Boolean> values) {
            addCriterion("ep_Delete in", values, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteNotIn(List<Boolean> values) {
            addCriterion("ep_Delete not in", values, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("ep_Delete between", value1, value2, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ep_Delete not between", value1, value2, "epDelete");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeIsNull() {
            addCriterion("ep_DeleteTime is null");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeIsNotNull() {
            addCriterion("ep_DeleteTime is not null");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeEqualTo(Date value) {
            addCriterion("ep_DeleteTime =", value, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeNotEqualTo(Date value) {
            addCriterion("ep_DeleteTime <>", value, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeGreaterThan(Date value) {
            addCriterion("ep_DeleteTime >", value, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ep_DeleteTime >=", value, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeLessThan(Date value) {
            addCriterion("ep_DeleteTime <", value, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeLessThanOrEqualTo(Date value) {
            addCriterion("ep_DeleteTime <=", value, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeIn(List<Date> values) {
            addCriterion("ep_DeleteTime in", values, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeNotIn(List<Date> values) {
            addCriterion("ep_DeleteTime not in", values, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeBetween(Date value1, Date value2) {
            addCriterion("ep_DeleteTime between", value1, value2, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andEpDeletetimeNotBetween(Date value1, Date value2) {
            addCriterion("ep_DeleteTime not between", value1, value2, "epDeletetime");
            return (Criteria) this;
        }

        public Criteria andDelectuserIsNull() {
            addCriterion("DelectUser is null");
            return (Criteria) this;
        }

        public Criteria andDelectuserIsNotNull() {
            addCriterion("DelectUser is not null");
            return (Criteria) this;
        }

        public Criteria andDelectuserEqualTo(String value) {
            addCriterion("DelectUser =", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserNotEqualTo(String value) {
            addCriterion("DelectUser <>", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserGreaterThan(String value) {
            addCriterion("DelectUser >", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserGreaterThanOrEqualTo(String value) {
            addCriterion("DelectUser >=", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserLessThan(String value) {
            addCriterion("DelectUser <", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserLessThanOrEqualTo(String value) {
            addCriterion("DelectUser <=", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserLike(String value) {
            addCriterion("DelectUser like", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserNotLike(String value) {
            addCriterion("DelectUser not like", value, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserIn(List<String> values) {
            addCriterion("DelectUser in", values, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserNotIn(List<String> values) {
            addCriterion("DelectUser not in", values, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserBetween(String value1, String value2) {
            addCriterion("DelectUser between", value1, value2, "delectuser");
            return (Criteria) this;
        }

        public Criteria andDelectuserNotBetween(String value1, String value2) {
            addCriterion("DelectUser not between", value1, value2, "delectuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 25 10:09:14 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_rolerightrelation
     *
     * @mbg.generated Mon Nov 25 10:09:14 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}