package com.buoyantec.dataobject;

import java.util.Date;

public class schoolDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.ts_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Long tsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.school_Name
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.school_nature
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private String schoolNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.school_Cood
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private String schoolCood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.Gen_time
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Date genTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.ep_Delete
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Boolean epDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.ep_DeleteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private Date epDeletetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_school.DelectUser
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    private String delectuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public schoolDO(Long tsId, String schoolName, String schoolNature, String schoolCood, Date genTime, Boolean epDelete, Date epDeletetime, String delectuser) {
        this.tsId = tsId;
        this.schoolName = schoolName;
        this.schoolNature = schoolNature;
        this.schoolCood = schoolCood;
        this.genTime = genTime;
        this.epDelete = epDelete;
        this.epDeletetime = epDeletetime;
        this.delectuser = delectuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_school
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public schoolDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.ts_id
     *
     * @return the value of t_school.ts_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Long getTsId() {
        return tsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.ts_id
     *
     * @param tsId the value for t_school.ts_id
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setTsId(Long tsId) {
        this.tsId = tsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.school_Name
     *
     * @return the value of t_school.school_Name
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.school_Name
     *
     * @param schoolName the value for t_school.school_Name
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.school_nature
     *
     * @return the value of t_school.school_nature
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public String getSchoolNature() {
        return schoolNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.school_nature
     *
     * @param schoolNature the value for t_school.school_nature
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setSchoolNature(String schoolNature) {
        this.schoolNature = schoolNature == null ? null : schoolNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.school_Cood
     *
     * @return the value of t_school.school_Cood
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public String getSchoolCood() {
        return schoolCood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.school_Cood
     *
     * @param schoolCood the value for t_school.school_Cood
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setSchoolCood(String schoolCood) {
        this.schoolCood = schoolCood == null ? null : schoolCood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.Gen_time
     *
     * @return the value of t_school.Gen_time
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Date getGenTime() {
        return genTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.Gen_time
     *
     * @param genTime the value for t_school.Gen_time
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setGenTime(Date genTime) {
        this.genTime = genTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.ep_Delete
     *
     * @return the value of t_school.ep_Delete
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Boolean getEpDelete() {
        return epDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.ep_Delete
     *
     * @param epDelete the value for t_school.ep_Delete
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setEpDelete(Boolean epDelete) {
        this.epDelete = epDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.ep_DeleteTime
     *
     * @return the value of t_school.ep_DeleteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public Date getEpDeletetime() {
        return epDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.ep_DeleteTime
     *
     * @param epDeletetime the value for t_school.ep_DeleteTime
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setEpDeletetime(Date epDeletetime) {
        this.epDeletetime = epDeletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_school.DelectUser
     *
     * @return the value of t_school.DelectUser
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public String getDelectuser() {
        return delectuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_school.DelectUser
     *
     * @param delectuser the value for t_school.DelectUser
     *
     * @mbg.generated Mon Nov 25 17:04:01 CST 2019
     */
    public void setDelectuser(String delectuser) {
        this.delectuser = delectuser == null ? null : delectuser.trim();
    }
}