package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TJobReviewerDOExample {
    public int getStartRow() {
        return StartRow;
    }

    public void setStartRow(int startRow) {
        StartRow = startRow;
    }

    public int getPageSize() {
        return PageSize;
    }

    public void setPageSize(int pageSize) {
        PageSize = pageSize;
    }

    protected  int StartRow;
    protected  int PageSize;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public TJobReviewerDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTjrIdIsNull() {
            addCriterion("tjr_ID is null");
            return (Criteria) this;
        }

        public Criteria andTjrIdIsNotNull() {
            addCriterion("tjr_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTjrIdEqualTo(Long value) {
            addCriterion("tjr_ID =", value, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdNotEqualTo(Long value) {
            addCriterion("tjr_ID <>", value, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdGreaterThan(Long value) {
            addCriterion("tjr_ID >", value, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tjr_ID >=", value, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdLessThan(Long value) {
            addCriterion("tjr_ID <", value, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdLessThanOrEqualTo(Long value) {
            addCriterion("tjr_ID <=", value, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdIn(List<Long> values) {
            addCriterion("tjr_ID in", values, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdNotIn(List<Long> values) {
            addCriterion("tjr_ID not in", values, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdBetween(Long value1, Long value2) {
            addCriterion("tjr_ID between", value1, value2, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjrIdNotBetween(Long value1, Long value2) {
            addCriterion("tjr_ID not between", value1, value2, "tjrId");
            return (Criteria) this;
        }

        public Criteria andTjIdIsNull() {
            addCriterion("tj_ID is null");
            return (Criteria) this;
        }

        public Criteria andTjIdIsNotNull() {
            addCriterion("tj_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTjIdEqualTo(Long value) {
            addCriterion("tj_ID =", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotEqualTo(Long value) {
            addCriterion("tj_ID <>", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdGreaterThan(Long value) {
            addCriterion("tj_ID >", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_ID >=", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLessThan(Long value) {
            addCriterion("tj_ID <", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLessThanOrEqualTo(Long value) {
            addCriterion("tj_ID <=", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdIn(List<Long> values) {
            addCriterion("tj_ID in", values, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotIn(List<Long> values) {
            addCriterion("tj_ID not in", values, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdBetween(Long value1, Long value2) {
            addCriterion("tj_ID between", value1, value2, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotBetween(Long value1, Long value2) {
            addCriterion("tj_ID not between", value1, value2, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerIsNull() {
            addCriterion("tjr_ISReviewer is null");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerIsNotNull() {
            addCriterion("tjr_ISReviewer is not null");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerEqualTo(Boolean value) {
            addCriterion("tjr_ISReviewer =", value, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerNotEqualTo(Boolean value) {
            addCriterion("tjr_ISReviewer <>", value, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerGreaterThan(Boolean value) {
            addCriterion("tjr_ISReviewer >", value, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tjr_ISReviewer >=", value, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerLessThan(Boolean value) {
            addCriterion("tjr_ISReviewer <", value, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerLessThanOrEqualTo(Boolean value) {
            addCriterion("tjr_ISReviewer <=", value, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerIn(List<Boolean> values) {
            addCriterion("tjr_ISReviewer in", values, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerNotIn(List<Boolean> values) {
            addCriterion("tjr_ISReviewer not in", values, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerBetween(Boolean value1, Boolean value2) {
            addCriterion("tjr_ISReviewer between", value1, value2, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrIsreviewerNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tjr_ISReviewer not between", value1, value2, "tjrIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjrResultIsNull() {
            addCriterion("tjr_result is null");
            return (Criteria) this;
        }

        public Criteria andTjrResultIsNotNull() {
            addCriterion("tjr_result is not null");
            return (Criteria) this;
        }

        public Criteria andTjrResultEqualTo(Boolean value) {
            addCriterion("tjr_result =", value, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultNotEqualTo(Boolean value) {
            addCriterion("tjr_result <>", value, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultGreaterThan(Boolean value) {
            addCriterion("tjr_result >", value, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tjr_result >=", value, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultLessThan(Boolean value) {
            addCriterion("tjr_result <", value, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultLessThanOrEqualTo(Boolean value) {
            addCriterion("tjr_result <=", value, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultIn(List<Boolean> values) {
            addCriterion("tjr_result in", values, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultNotIn(List<Boolean> values) {
            addCriterion("tjr_result not in", values, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultBetween(Boolean value1, Boolean value2) {
            addCriterion("tjr_result between", value1, value2, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrResultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tjr_result not between", value1, value2, "tjrResult");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonIsNull() {
            addCriterion("tjr_DenialReason is null");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonIsNotNull() {
            addCriterion("tjr_DenialReason is not null");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonEqualTo(String value) {
            addCriterion("tjr_DenialReason =", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonNotEqualTo(String value) {
            addCriterion("tjr_DenialReason <>", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonGreaterThan(String value) {
            addCriterion("tjr_DenialReason >", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonGreaterThanOrEqualTo(String value) {
            addCriterion("tjr_DenialReason >=", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonLessThan(String value) {
            addCriterion("tjr_DenialReason <", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonLessThanOrEqualTo(String value) {
            addCriterion("tjr_DenialReason <=", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonLike(String value) {
            addCriterion("tjr_DenialReason like", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonNotLike(String value) {
            addCriterion("tjr_DenialReason not like", value, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonIn(List<String> values) {
            addCriterion("tjr_DenialReason in", values, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonNotIn(List<String> values) {
            addCriterion("tjr_DenialReason not in", values, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonBetween(String value1, String value2) {
            addCriterion("tjr_DenialReason between", value1, value2, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrDenialreasonNotBetween(String value1, String value2) {
            addCriterion("tjr_DenialReason not between", value1, value2, "tjrDenialreason");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridIsNull() {
            addCriterion("tjr_ReviewerUserID is null");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridIsNotNull() {
            addCriterion("tjr_ReviewerUserID is not null");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridEqualTo(Long value) {
            addCriterion("tjr_ReviewerUserID =", value, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridNotEqualTo(Long value) {
            addCriterion("tjr_ReviewerUserID <>", value, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridGreaterThan(Long value) {
            addCriterion("tjr_ReviewerUserID >", value, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridGreaterThanOrEqualTo(Long value) {
            addCriterion("tjr_ReviewerUserID >=", value, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridLessThan(Long value) {
            addCriterion("tjr_ReviewerUserID <", value, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridLessThanOrEqualTo(Long value) {
            addCriterion("tjr_ReviewerUserID <=", value, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridIn(List<Long> values) {
            addCriterion("tjr_ReviewerUserID in", values, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridNotIn(List<Long> values) {
            addCriterion("tjr_ReviewerUserID not in", values, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridBetween(Long value1, Long value2) {
            addCriterion("tjr_ReviewerUserID between", value1, value2, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrRevieweruseridNotBetween(Long value1, Long value2) {
            addCriterion("tjr_ReviewerUserID not between", value1, value2, "tjrRevieweruserid");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeIsNull() {
            addCriterion("tjr_ReviewerTime is null");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeIsNotNull() {
            addCriterion("tjr_ReviewerTime is not null");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeEqualTo(Date value) {
            addCriterion("tjr_ReviewerTime =", value, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeNotEqualTo(Date value) {
            addCriterion("tjr_ReviewerTime <>", value, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeGreaterThan(Date value) {
            addCriterion("tjr_ReviewerTime >", value, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tjr_ReviewerTime >=", value, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeLessThan(Date value) {
            addCriterion("tjr_ReviewerTime <", value, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeLessThanOrEqualTo(Date value) {
            addCriterion("tjr_ReviewerTime <=", value, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeIn(List<Date> values) {
            addCriterion("tjr_ReviewerTime in", values, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeNotIn(List<Date> values) {
            addCriterion("tjr_ReviewerTime not in", values, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeBetween(Date value1, Date value2) {
            addCriterion("tjr_ReviewerTime between", value1, value2, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrReviewertimeNotBetween(Date value1, Date value2) {
            addCriterion("tjr_ReviewerTime not between", value1, value2, "tjrReviewertime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeIsNull() {
            addCriterion("tjr_CreateDateTime is null");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeIsNotNull() {
            addCriterion("tjr_CreateDateTime is not null");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeEqualTo(Date value) {
            addCriterion("tjr_CreateDateTime =", value, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeNotEqualTo(Date value) {
            addCriterion("tjr_CreateDateTime <>", value, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeGreaterThan(Date value) {
            addCriterion("tjr_CreateDateTime >", value, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tjr_CreateDateTime >=", value, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeLessThan(Date value) {
            addCriterion("tjr_CreateDateTime <", value, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeLessThanOrEqualTo(Date value) {
            addCriterion("tjr_CreateDateTime <=", value, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeIn(List<Date> values) {
            addCriterion("tjr_CreateDateTime in", values, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeNotIn(List<Date> values) {
            addCriterion("tjr_CreateDateTime not in", values, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeBetween(Date value1, Date value2) {
            addCriterion("tjr_CreateDateTime between", value1, value2, "tjrCreatedatetime");
            return (Criteria) this;
        }

        public Criteria andTjrCreatedatetimeNotBetween(Date value1, Date value2) {
            addCriterion("tjr_CreateDateTime not between", value1, value2, "tjrCreatedatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jobreviewer
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 27 10:14:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jobreviewer
     *
     * @mbg.generated Fri Dec 27 10:14:49 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}