package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TJobDOExample {

    public int getPageSize() {
        return PageSize;
    }

    public void setPageSize(int pageSize) {
        PageSize = pageSize;
    }

    public int getStartRow() {
        return StartRow;
    }

    public void setStartRow(int startRow) {
        StartRow = startRow;
    }

    protected  int PageSize;
    protected  int StartRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public TJobDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTjIdIsNull() {
            addCriterion("tj_ID is null");
            return (Criteria) this;
        }

        public Criteria andTjIdIsNotNull() {
            addCriterion("tj_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTjIdEqualTo(Long value) {
            addCriterion("tj_ID =", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotEqualTo(Long value) {
            addCriterion("tj_ID <>", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdGreaterThan(Long value) {
            addCriterion("tj_ID >", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_ID >=", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLessThan(Long value) {
            addCriterion("tj_ID <", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLessThanOrEqualTo(Long value) {
            addCriterion("tj_ID <=", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdIn(List<Long> values) {
            addCriterion("tj_ID in", values, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotIn(List<Long> values) {
            addCriterion("tj_ID not in", values, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdBetween(Long value1, Long value2) {
            addCriterion("tj_ID between", value1, value2, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotBetween(Long value1, Long value2) {
            addCriterion("tj_ID not between", value1, value2, "tjId");
            return (Criteria) this;
        }

        public Criteria andTeIdIsNull() {
            addCriterion("te_id is null");
            return (Criteria) this;
        }

        public Criteria andTeIdIsNotNull() {
            addCriterion("te_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeIdEqualTo(Long value) {
            addCriterion("te_id =", value, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdNotEqualTo(Long value) {
            addCriterion("te_id <>", value, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdGreaterThan(Long value) {
            addCriterion("te_id >", value, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("te_id >=", value, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdLessThan(Long value) {
            addCriterion("te_id <", value, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdLessThanOrEqualTo(Long value) {
            addCriterion("te_id <=", value, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdIn(List<Long> values) {
            addCriterion("te_id in", values, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdNotIn(List<Long> values) {
            addCriterion("te_id not in", values, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdBetween(Long value1, Long value2) {
            addCriterion("te_id between", value1, value2, "teId");
            return (Criteria) this;
        }

        public Criteria andTeIdNotBetween(Long value1, Long value2) {
            addCriterion("te_id not between", value1, value2, "teId");
            return (Criteria) this;
        }

        public Criteria andTjNameIsNull() {
            addCriterion("tj_Name is null");
            return (Criteria) this;
        }

        public Criteria andTjNameIsNotNull() {
            addCriterion("tj_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTjNameEqualTo(String value) {
            addCriterion("tj_Name =", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameNotEqualTo(String value) {
            addCriterion("tj_Name <>", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameGreaterThan(String value) {
            addCriterion("tj_Name >", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameGreaterThanOrEqualTo(String value) {
            addCriterion("tj_Name >=", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameLessThan(String value) {
            addCriterion("tj_Name <", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameLessThanOrEqualTo(String value) {
            addCriterion("tj_Name <=", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameLike(String value) {
            addCriterion("tj_Name like", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameNotLike(String value) {
            addCriterion("tj_Name not like", value, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameIn(List<String> values) {
            addCriterion("tj_Name in", values, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameNotIn(List<String> values) {
            addCriterion("tj_Name not in", values, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameBetween(String value1, String value2) {
            addCriterion("tj_Name between", value1, value2, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjNameNotBetween(String value1, String value2) {
            addCriterion("tj_Name not between", value1, value2, "tjName");
            return (Criteria) this;
        }

        public Criteria andTjTypeIsNull() {
            addCriterion("tj_Type is null");
            return (Criteria) this;
        }

        public Criteria andTjTypeIsNotNull() {
            addCriterion("tj_Type is not null");
            return (Criteria) this;
        }

        public Criteria andTjTypeEqualTo(String value) {
            addCriterion("tj_Type =", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeNotEqualTo(String value) {
            addCriterion("tj_Type <>", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeGreaterThan(String value) {
            addCriterion("tj_Type >", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeGreaterThanOrEqualTo(String value) {
            addCriterion("tj_Type >=", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeLessThan(String value) {
            addCriterion("tj_Type <", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeLessThanOrEqualTo(String value) {
            addCriterion("tj_Type <=", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeLike(String value) {
            addCriterion("tj_Type like", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeNotLike(String value) {
            addCriterion("tj_Type not like", value, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeIn(List<String> values) {
            addCriterion("tj_Type in", values, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeNotIn(List<String> values) {
            addCriterion("tj_Type not in", values, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeBetween(String value1, String value2) {
            addCriterion("tj_Type between", value1, value2, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjTypeNotBetween(String value1, String value2) {
            addCriterion("tj_Type not between", value1, value2, "tjType");
            return (Criteria) this;
        }

        public Criteria andTjClassificationIsNull() {
            addCriterion("tj_classification is null");
            return (Criteria) this;
        }

        public Criteria andTjClassificationIsNotNull() {
            addCriterion("tj_classification is not null");
            return (Criteria) this;
        }

        public Criteria andTjClassificationEqualTo(String value) {
            addCriterion("tj_classification =", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationNotEqualTo(String value) {
            addCriterion("tj_classification <>", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationGreaterThan(String value) {
            addCriterion("tj_classification >", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationGreaterThanOrEqualTo(String value) {
            addCriterion("tj_classification >=", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationLessThan(String value) {
            addCriterion("tj_classification <", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationLessThanOrEqualTo(String value) {
            addCriterion("tj_classification <=", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationLike(String value) {
            addCriterion("tj_classification like", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationNotLike(String value) {
            addCriterion("tj_classification not like", value, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationIn(List<String> values) {
            addCriterion("tj_classification in", values, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationNotIn(List<String> values) {
            addCriterion("tj_classification not in", values, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationBetween(String value1, String value2) {
            addCriterion("tj_classification between", value1, value2, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjClassificationNotBetween(String value1, String value2) {
            addCriterion("tj_classification not between", value1, value2, "tjClassification");
            return (Criteria) this;
        }

        public Criteria andTjPeopleIsNull() {
            addCriterion("tj_people is null");
            return (Criteria) this;
        }

        public Criteria andTjPeopleIsNotNull() {
            addCriterion("tj_people is not null");
            return (Criteria) this;
        }

        public Criteria andTjPeopleEqualTo(Long value) {
            addCriterion("tj_people =", value, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleNotEqualTo(Long value) {
            addCriterion("tj_people <>", value, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleGreaterThan(Long value) {
            addCriterion("tj_people >", value, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_people >=", value, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleLessThan(Long value) {
            addCriterion("tj_people <", value, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleLessThanOrEqualTo(Long value) {
            addCriterion("tj_people <=", value, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleIn(List<Long> values) {
            addCriterion("tj_people in", values, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleNotIn(List<Long> values) {
            addCriterion("tj_people not in", values, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleBetween(Long value1, Long value2) {
            addCriterion("tj_people between", value1, value2, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjPeopleNotBetween(Long value1, Long value2) {
            addCriterion("tj_people not between", value1, value2, "tjPeople");
            return (Criteria) this;
        }

        public Criteria andTjSexIsNull() {
            addCriterion("tj_Sex is null");
            return (Criteria) this;
        }

        public Criteria andTjSexIsNotNull() {
            addCriterion("tj_Sex is not null");
            return (Criteria) this;
        }

        public Criteria andTjSexEqualTo(String value) {
            addCriterion("tj_Sex =", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexNotEqualTo(String value) {
            addCriterion("tj_Sex <>", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexGreaterThan(String value) {
            addCriterion("tj_Sex >", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexGreaterThanOrEqualTo(String value) {
            addCriterion("tj_Sex >=", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexLessThan(String value) {
            addCriterion("tj_Sex <", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexLessThanOrEqualTo(String value) {
            addCriterion("tj_Sex <=", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexLike(String value) {
            addCriterion("tj_Sex like", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexNotLike(String value) {
            addCriterion("tj_Sex not like", value, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexIn(List<String> values) {
            addCriterion("tj_Sex in", values, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexNotIn(List<String> values) {
            addCriterion("tj_Sex not in", values, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexBetween(String value1, String value2) {
            addCriterion("tj_Sex between", value1, value2, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjSexNotBetween(String value1, String value2) {
            addCriterion("tj_Sex not between", value1, value2, "tjSex");
            return (Criteria) this;
        }

        public Criteria andTjProfeIsNull() {
            addCriterion("tj_profe is null");
            return (Criteria) this;
        }

        public Criteria andTjProfeIsNotNull() {
            addCriterion("tj_profe is not null");
            return (Criteria) this;
        }

        public Criteria andTjProfeEqualTo(String value) {
            addCriterion("tj_profe =", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeNotEqualTo(String value) {
            addCriterion("tj_profe <>", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeGreaterThan(String value) {
            addCriterion("tj_profe >", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeGreaterThanOrEqualTo(String value) {
            addCriterion("tj_profe >=", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeLessThan(String value) {
            addCriterion("tj_profe <", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeLessThanOrEqualTo(String value) {
            addCriterion("tj_profe <=", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeLike(String value) {
            addCriterion("tj_profe like", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeNotLike(String value) {
            addCriterion("tj_profe not like", value, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeIn(List<String> values) {
            addCriterion("tj_profe in", values, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeNotIn(List<String> values) {
            addCriterion("tj_profe not in", values, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeBetween(String value1, String value2) {
            addCriterion("tj_profe between", value1, value2, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjProfeNotBetween(String value1, String value2) {
            addCriterion("tj_profe not between", value1, value2, "tjProfe");
            return (Criteria) this;
        }

        public Criteria andTjEducationIsNull() {
            addCriterion("tj_education is null");
            return (Criteria) this;
        }

        public Criteria andTjEducationIsNotNull() {
            addCriterion("tj_education is not null");
            return (Criteria) this;
        }

        public Criteria andTjEducationEqualTo(String value) {
            addCriterion("tj_education =", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationNotEqualTo(String value) {
            addCriterion("tj_education <>", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationGreaterThan(String value) {
            addCriterion("tj_education >", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationGreaterThanOrEqualTo(String value) {
            addCriterion("tj_education >=", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationLessThan(String value) {
            addCriterion("tj_education <", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationLessThanOrEqualTo(String value) {
            addCriterion("tj_education <=", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationLike(String value) {
            addCriterion("tj_education like", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationNotLike(String value) {
            addCriterion("tj_education not like", value, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationIn(List<String> values) {
            addCriterion("tj_education in", values, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationNotIn(List<String> values) {
            addCriterion("tj_education not in", values, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationBetween(String value1, String value2) {
            addCriterion("tj_education between", value1, value2, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjEducationNotBetween(String value1, String value2) {
            addCriterion("tj_education not between", value1, value2, "tjEducation");
            return (Criteria) this;
        }

        public Criteria andTjAreaIsNull() {
            addCriterion("tj_area is null");
            return (Criteria) this;
        }

        public Criteria andTjAreaIsNotNull() {
            addCriterion("tj_area is not null");
            return (Criteria) this;
        }

        public Criteria andTjAreaEqualTo(String value) {
            addCriterion("tj_area =", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaNotEqualTo(String value) {
            addCriterion("tj_area <>", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaGreaterThan(String value) {
            addCriterion("tj_area >", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaGreaterThanOrEqualTo(String value) {
            addCriterion("tj_area >=", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaLessThan(String value) {
            addCriterion("tj_area <", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaLessThanOrEqualTo(String value) {
            addCriterion("tj_area <=", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaLike(String value) {
            addCriterion("tj_area like", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaNotLike(String value) {
            addCriterion("tj_area not like", value, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaIn(List<String> values) {
            addCriterion("tj_area in", values, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaNotIn(List<String> values) {
            addCriterion("tj_area not in", values, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaBetween(String value1, String value2) {
            addCriterion("tj_area between", value1, value2, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjAreaNotBetween(String value1, String value2) {
            addCriterion("tj_area not between", value1, value2, "tjArea");
            return (Criteria) this;
        }

        public Criteria andTjPayIsNull() {
            addCriterion("tj_pay is null");
            return (Criteria) this;
        }

        public Criteria andTjPayIsNotNull() {
            addCriterion("tj_pay is not null");
            return (Criteria) this;
        }

        public Criteria andTjPayEqualTo(String value) {
            addCriterion("tj_pay =", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayNotEqualTo(String value) {
            addCriterion("tj_pay <>", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayGreaterThan(String value) {
            addCriterion("tj_pay >", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayGreaterThanOrEqualTo(String value) {
            addCriterion("tj_pay >=", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayLessThan(String value) {
            addCriterion("tj_pay <", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayLessThanOrEqualTo(String value) {
            addCriterion("tj_pay <=", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayLike(String value) {
            addCriterion("tj_pay like", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayNotLike(String value) {
            addCriterion("tj_pay not like", value, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayIn(List<String> values) {
            addCriterion("tj_pay in", values, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayNotIn(List<String> values) {
            addCriterion("tj_pay not in", values, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayBetween(String value1, String value2) {
            addCriterion("tj_pay between", value1, value2, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjPayNotBetween(String value1, String value2) {
            addCriterion("tj_pay not between", value1, value2, "tjPay");
            return (Criteria) this;
        }

        public Criteria andTjFlIsNull() {
            addCriterion("tj_FL is null");
            return (Criteria) this;
        }

        public Criteria andTjFlIsNotNull() {
            addCriterion("tj_FL is not null");
            return (Criteria) this;
        }

        public Criteria andTjFlEqualTo(String value) {
            addCriterion("tj_FL =", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlNotEqualTo(String value) {
            addCriterion("tj_FL <>", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlGreaterThan(String value) {
            addCriterion("tj_FL >", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlGreaterThanOrEqualTo(String value) {
            addCriterion("tj_FL >=", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlLessThan(String value) {
            addCriterion("tj_FL <", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlLessThanOrEqualTo(String value) {
            addCriterion("tj_FL <=", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlLike(String value) {
            addCriterion("tj_FL like", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlNotLike(String value) {
            addCriterion("tj_FL not like", value, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlIn(List<String> values) {
            addCriterion("tj_FL in", values, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlNotIn(List<String> values) {
            addCriterion("tj_FL not in", values, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlBetween(String value1, String value2) {
            addCriterion("tj_FL between", value1, value2, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjFlNotBetween(String value1, String value2) {
            addCriterion("tj_FL not between", value1, value2, "tjFl");
            return (Criteria) this;
        }

        public Criteria andTjComputerIsNull() {
            addCriterion("tj_computer is null");
            return (Criteria) this;
        }

        public Criteria andTjComputerIsNotNull() {
            addCriterion("tj_computer is not null");
            return (Criteria) this;
        }

        public Criteria andTjComputerEqualTo(String value) {
            addCriterion("tj_computer =", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerNotEqualTo(String value) {
            addCriterion("tj_computer <>", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerGreaterThan(String value) {
            addCriterion("tj_computer >", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerGreaterThanOrEqualTo(String value) {
            addCriterion("tj_computer >=", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerLessThan(String value) {
            addCriterion("tj_computer <", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerLessThanOrEqualTo(String value) {
            addCriterion("tj_computer <=", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerLike(String value) {
            addCriterion("tj_computer like", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerNotLike(String value) {
            addCriterion("tj_computer not like", value, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerIn(List<String> values) {
            addCriterion("tj_computer in", values, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerNotIn(List<String> values) {
            addCriterion("tj_computer not in", values, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerBetween(String value1, String value2) {
            addCriterion("tj_computer between", value1, value2, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjComputerNotBetween(String value1, String value2) {
            addCriterion("tj_computer not between", value1, value2, "tjComputer");
            return (Criteria) this;
        }

        public Criteria andTjOtherIsNull() {
            addCriterion("tj_other is null");
            return (Criteria) this;
        }

        public Criteria andTjOtherIsNotNull() {
            addCriterion("tj_other is not null");
            return (Criteria) this;
        }

        public Criteria andTjOtherEqualTo(String value) {
            addCriterion("tj_other =", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherNotEqualTo(String value) {
            addCriterion("tj_other <>", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherGreaterThan(String value) {
            addCriterion("tj_other >", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherGreaterThanOrEqualTo(String value) {
            addCriterion("tj_other >=", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherLessThan(String value) {
            addCriterion("tj_other <", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherLessThanOrEqualTo(String value) {
            addCriterion("tj_other <=", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherLike(String value) {
            addCriterion("tj_other like", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherNotLike(String value) {
            addCriterion("tj_other not like", value, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherIn(List<String> values) {
            addCriterion("tj_other in", values, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherNotIn(List<String> values) {
            addCriterion("tj_other not in", values, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherBetween(String value1, String value2) {
            addCriterion("tj_other between", value1, value2, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjOtherNotBetween(String value1, String value2) {
            addCriterion("tj_other not between", value1, value2, "tjOther");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionIsNull() {
            addCriterion("tj_description is null");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionIsNotNull() {
            addCriterion("tj_description is not null");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionEqualTo(String value) {
            addCriterion("tj_description =", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionNotEqualTo(String value) {
            addCriterion("tj_description <>", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionGreaterThan(String value) {
            addCriterion("tj_description >", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("tj_description >=", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionLessThan(String value) {
            addCriterion("tj_description <", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionLessThanOrEqualTo(String value) {
            addCriterion("tj_description <=", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionLike(String value) {
            addCriterion("tj_description like", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionNotLike(String value) {
            addCriterion("tj_description not like", value, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionIn(List<String> values) {
            addCriterion("tj_description in", values, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionNotIn(List<String> values) {
            addCriterion("tj_description not in", values, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionBetween(String value1, String value2) {
            addCriterion("tj_description between", value1, value2, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDescriptionNotBetween(String value1, String value2) {
            addCriterion("tj_description not between", value1, value2, "tjDescription");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineIsNull() {
            addCriterion("tj_deadline is null");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineIsNotNull() {
            addCriterion("tj_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineEqualTo(Date value) {
            addCriterion("tj_deadline =", value, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineNotEqualTo(Date value) {
            addCriterion("tj_deadline <>", value, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineGreaterThan(Date value) {
            addCriterion("tj_deadline >", value, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("tj_deadline >=", value, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineLessThan(Date value) {
            addCriterion("tj_deadline <", value, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("tj_deadline <=", value, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineIn(List<Date> values) {
            addCriterion("tj_deadline in", values, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineNotIn(List<Date> values) {
            addCriterion("tj_deadline not in", values, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineBetween(Date value1, Date value2) {
            addCriterion("tj_deadline between", value1, value2, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("tj_deadline not between", value1, value2, "tjDeadline");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateIsNull() {
            addCriterion("tj_Releasedate is null");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateIsNotNull() {
            addCriterion("tj_Releasedate is not null");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateEqualTo(Date value) {
            addCriterion("tj_Releasedate =", value, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateNotEqualTo(Date value) {
            addCriterion("tj_Releasedate <>", value, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateGreaterThan(Date value) {
            addCriterion("tj_Releasedate >", value, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateGreaterThanOrEqualTo(Date value) {
            addCriterion("tj_Releasedate >=", value, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateLessThan(Date value) {
            addCriterion("tj_Releasedate <", value, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateLessThanOrEqualTo(Date value) {
            addCriterion("tj_Releasedate <=", value, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateIn(List<Date> values) {
            addCriterion("tj_Releasedate in", values, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateNotIn(List<Date> values) {
            addCriterion("tj_Releasedate not in", values, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateBetween(Date value1, Date value2) {
            addCriterion("tj_Releasedate between", value1, value2, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjReleasedateNotBetween(Date value1, Date value2) {
            addCriterion("tj_Releasedate not between", value1, value2, "tjReleasedate");
            return (Criteria) this;
        }

        public Criteria andTjPopularityIsNull() {
            addCriterion("tj_Popularity is null");
            return (Criteria) this;
        }

        public Criteria andTjPopularityIsNotNull() {
            addCriterion("tj_Popularity is not null");
            return (Criteria) this;
        }

        public Criteria andTjPopularityEqualTo(Long value) {
            addCriterion("tj_Popularity =", value, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityNotEqualTo(Long value) {
            addCriterion("tj_Popularity <>", value, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityGreaterThan(Long value) {
            addCriterion("tj_Popularity >", value, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_Popularity >=", value, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityLessThan(Long value) {
            addCriterion("tj_Popularity <", value, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityLessThanOrEqualTo(Long value) {
            addCriterion("tj_Popularity <=", value, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityIn(List<Long> values) {
            addCriterion("tj_Popularity in", values, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityNotIn(List<Long> values) {
            addCriterion("tj_Popularity not in", values, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityBetween(Long value1, Long value2) {
            addCriterion("tj_Popularity between", value1, value2, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjPopularityNotBetween(Long value1, Long value2) {
            addCriterion("tj_Popularity not between", value1, value2, "tjPopularity");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridIsNull() {
            addCriterion("tj_CreaterUserID is null");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridIsNotNull() {
            addCriterion("tj_CreaterUserID is not null");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridEqualTo(Long value) {
            addCriterion("tj_CreaterUserID =", value, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridNotEqualTo(Long value) {
            addCriterion("tj_CreaterUserID <>", value, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridGreaterThan(Long value) {
            addCriterion("tj_CreaterUserID >", value, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_CreaterUserID >=", value, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridLessThan(Long value) {
            addCriterion("tj_CreaterUserID <", value, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridLessThanOrEqualTo(Long value) {
            addCriterion("tj_CreaterUserID <=", value, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridIn(List<Long> values) {
            addCriterion("tj_CreaterUserID in", values, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridNotIn(List<Long> values) {
            addCriterion("tj_CreaterUserID not in", values, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridBetween(Long value1, Long value2) {
            addCriterion("tj_CreaterUserID between", value1, value2, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjCreateruseridNotBetween(Long value1, Long value2) {
            addCriterion("tj_CreaterUserID not between", value1, value2, "tjCreateruserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridIsNull() {
            addCriterion("tj_ReleaseUserID is null");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridIsNotNull() {
            addCriterion("tj_ReleaseUserID is not null");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridEqualTo(Long value) {
            addCriterion("tj_ReleaseUserID =", value, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridNotEqualTo(Long value) {
            addCriterion("tj_ReleaseUserID <>", value, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridGreaterThan(Long value) {
            addCriterion("tj_ReleaseUserID >", value, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_ReleaseUserID >=", value, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridLessThan(Long value) {
            addCriterion("tj_ReleaseUserID <", value, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridLessThanOrEqualTo(Long value) {
            addCriterion("tj_ReleaseUserID <=", value, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridIn(List<Long> values) {
            addCriterion("tj_ReleaseUserID in", values, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridNotIn(List<Long> values) {
            addCriterion("tj_ReleaseUserID not in", values, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridBetween(Long value1, Long value2) {
            addCriterion("tj_ReleaseUserID between", value1, value2, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjReleaseuseridNotBetween(Long value1, Long value2) {
            addCriterion("tj_ReleaseUserID not between", value1, value2, "tjReleaseuserid");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonIsNull() {
            addCriterion("tj_ContactPerson is null");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonIsNotNull() {
            addCriterion("tj_ContactPerson is not null");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonEqualTo(String value) {
            addCriterion("tj_ContactPerson =", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonNotEqualTo(String value) {
            addCriterion("tj_ContactPerson <>", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonGreaterThan(String value) {
            addCriterion("tj_ContactPerson >", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonGreaterThanOrEqualTo(String value) {
            addCriterion("tj_ContactPerson >=", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonLessThan(String value) {
            addCriterion("tj_ContactPerson <", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonLessThanOrEqualTo(String value) {
            addCriterion("tj_ContactPerson <=", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonLike(String value) {
            addCriterion("tj_ContactPerson like", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonNotLike(String value) {
            addCriterion("tj_ContactPerson not like", value, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonIn(List<String> values) {
            addCriterion("tj_ContactPerson in", values, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonNotIn(List<String> values) {
            addCriterion("tj_ContactPerson not in", values, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonBetween(String value1, String value2) {
            addCriterion("tj_ContactPerson between", value1, value2, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactpersonNotBetween(String value1, String value2) {
            addCriterion("tj_ContactPerson not between", value1, value2, "tjContactperson");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsIsNull() {
            addCriterion("tj_ContactDetails is null");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsIsNotNull() {
            addCriterion("tj_ContactDetails is not null");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsEqualTo(String value) {
            addCriterion("tj_ContactDetails =", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsNotEqualTo(String value) {
            addCriterion("tj_ContactDetails <>", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsGreaterThan(String value) {
            addCriterion("tj_ContactDetails >", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsGreaterThanOrEqualTo(String value) {
            addCriterion("tj_ContactDetails >=", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsLessThan(String value) {
            addCriterion("tj_ContactDetails <", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsLessThanOrEqualTo(String value) {
            addCriterion("tj_ContactDetails <=", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsLike(String value) {
            addCriterion("tj_ContactDetails like", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsNotLike(String value) {
            addCriterion("tj_ContactDetails not like", value, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsIn(List<String> values) {
            addCriterion("tj_ContactDetails in", values, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsNotIn(List<String> values) {
            addCriterion("tj_ContactDetails not in", values, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsBetween(String value1, String value2) {
            addCriterion("tj_ContactDetails between", value1, value2, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjContactdetailsNotBetween(String value1, String value2) {
            addCriterion("tj_ContactDetails not between", value1, value2, "tjContactdetails");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeIsNull() {
            addCriterion("tj_CreaterTime is null");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeIsNotNull() {
            addCriterion("tj_CreaterTime is not null");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeEqualTo(Date value) {
            addCriterion("tj_CreaterTime =", value, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeNotEqualTo(Date value) {
            addCriterion("tj_CreaterTime <>", value, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeGreaterThan(Date value) {
            addCriterion("tj_CreaterTime >", value, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tj_CreaterTime >=", value, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeLessThan(Date value) {
            addCriterion("tj_CreaterTime <", value, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeLessThanOrEqualTo(Date value) {
            addCriterion("tj_CreaterTime <=", value, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeIn(List<Date> values) {
            addCriterion("tj_CreaterTime in", values, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeNotIn(List<Date> values) {
            addCriterion("tj_CreaterTime not in", values, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeBetween(Date value1, Date value2) {
            addCriterion("tj_CreaterTime between", value1, value2, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjCreatertimeNotBetween(Date value1, Date value2) {
            addCriterion("tj_CreaterTime not between", value1, value2, "tjCreatertime");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteIsNull() {
            addCriterion("tj_ISDelete is null");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteIsNotNull() {
            addCriterion("tj_ISDelete is not null");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteEqualTo(Boolean value) {
            addCriterion("tj_ISDelete =", value, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteNotEqualTo(Boolean value) {
            addCriterion("tj_ISDelete <>", value, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteGreaterThan(Boolean value) {
            addCriterion("tj_ISDelete >", value, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tj_ISDelete >=", value, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteLessThan(Boolean value) {
            addCriterion("tj_ISDelete <", value, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("tj_ISDelete <=", value, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteIn(List<Boolean> values) {
            addCriterion("tj_ISDelete in", values, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteNotIn(List<Boolean> values) {
            addCriterion("tj_ISDelete not in", values, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("tj_ISDelete between", value1, value2, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tj_ISDelete not between", value1, value2, "tjIsdelete");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridIsNull() {
            addCriterion("tj_DeleteUserID is null");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridIsNotNull() {
            addCriterion("tj_DeleteUserID is not null");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridEqualTo(Long value) {
            addCriterion("tj_DeleteUserID =", value, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridNotEqualTo(Long value) {
            addCriterion("tj_DeleteUserID <>", value, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridGreaterThan(Long value) {
            addCriterion("tj_DeleteUserID >", value, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_DeleteUserID >=", value, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridLessThan(Long value) {
            addCriterion("tj_DeleteUserID <", value, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridLessThanOrEqualTo(Long value) {
            addCriterion("tj_DeleteUserID <=", value, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridIn(List<Long> values) {
            addCriterion("tj_DeleteUserID in", values, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridNotIn(List<Long> values) {
            addCriterion("tj_DeleteUserID not in", values, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridBetween(Long value1, Long value2) {
            addCriterion("tj_DeleteUserID between", value1, value2, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeleteuseridNotBetween(Long value1, Long value2) {
            addCriterion("tj_DeleteUserID not between", value1, value2, "tjDeleteuserid");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeIsNull() {
            addCriterion("tj_DeleteTime is null");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeIsNotNull() {
            addCriterion("tj_DeleteTime is not null");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeEqualTo(Date value) {
            addCriterion("tj_DeleteTime =", value, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeNotEqualTo(Date value) {
            addCriterion("tj_DeleteTime <>", value, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeGreaterThan(Date value) {
            addCriterion("tj_DeleteTime >", value, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tj_DeleteTime >=", value, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeLessThan(Date value) {
            addCriterion("tj_DeleteTime <", value, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeLessThanOrEqualTo(Date value) {
            addCriterion("tj_DeleteTime <=", value, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeIn(List<Date> values) {
            addCriterion("tj_DeleteTime in", values, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeNotIn(List<Date> values) {
            addCriterion("tj_DeleteTime not in", values, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeBetween(Date value1, Date value2) {
            addCriterion("tj_DeleteTime between", value1, value2, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjDeletetimeNotBetween(Date value1, Date value2) {
            addCriterion("tj_DeleteTime not between", value1, value2, "tjDeletetime");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridIsNull() {
            addCriterion("tj_MidefUserID is null");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridIsNotNull() {
            addCriterion("tj_MidefUserID is not null");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridEqualTo(Long value) {
            addCriterion("tj_MidefUserID =", value, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridNotEqualTo(Long value) {
            addCriterion("tj_MidefUserID <>", value, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridGreaterThan(Long value) {
            addCriterion("tj_MidefUserID >", value, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridGreaterThanOrEqualTo(Long value) {
            addCriterion("tj_MidefUserID >=", value, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridLessThan(Long value) {
            addCriterion("tj_MidefUserID <", value, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridLessThanOrEqualTo(Long value) {
            addCriterion("tj_MidefUserID <=", value, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridIn(List<Long> values) {
            addCriterion("tj_MidefUserID in", values, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridNotIn(List<Long> values) {
            addCriterion("tj_MidefUserID not in", values, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridBetween(Long value1, Long value2) {
            addCriterion("tj_MidefUserID between", value1, value2, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMidefuseridNotBetween(Long value1, Long value2) {
            addCriterion("tj_MidefUserID not between", value1, value2, "tjMidefuserid");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeIsNull() {
            addCriterion("tj_MidefTime is null");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeIsNotNull() {
            addCriterion("tj_MidefTime is not null");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeEqualTo(Date value) {
            addCriterion("tj_MidefTime =", value, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeNotEqualTo(Date value) {
            addCriterion("tj_MidefTime <>", value, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeGreaterThan(Date value) {
            addCriterion("tj_MidefTime >", value, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tj_MidefTime >=", value, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeLessThan(Date value) {
            addCriterion("tj_MidefTime <", value, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeLessThanOrEqualTo(Date value) {
            addCriterion("tj_MidefTime <=", value, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeIn(List<Date> values) {
            addCriterion("tj_MidefTime in", values, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeNotIn(List<Date> values) {
            addCriterion("tj_MidefTime not in", values, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeBetween(Date value1, Date value2) {
            addCriterion("tj_MidefTime between", value1, value2, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjMideftimeNotBetween(Date value1, Date value2) {
            addCriterion("tj_MidefTime not between", value1, value2, "tjMideftime");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerIsNull() {
            addCriterion("tj_ISReviewer is null");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerIsNotNull() {
            addCriterion("tj_ISReviewer is not null");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerEqualTo(Boolean value) {
            addCriterion("tj_ISReviewer =", value, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerNotEqualTo(Boolean value) {
            addCriterion("tj_ISReviewer <>", value, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerGreaterThan(Boolean value) {
            addCriterion("tj_ISReviewer >", value, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tj_ISReviewer >=", value, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerLessThan(Boolean value) {
            addCriterion("tj_ISReviewer <", value, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerLessThanOrEqualTo(Boolean value) {
            addCriterion("tj_ISReviewer <=", value, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerIn(List<Boolean> values) {
            addCriterion("tj_ISReviewer in", values, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerNotIn(List<Boolean> values) {
            addCriterion("tj_ISReviewer not in", values, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerBetween(Boolean value1, Boolean value2) {
            addCriterion("tj_ISReviewer between", value1, value2, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjIsreviewerNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tj_ISReviewer not between", value1, value2, "tjIsreviewer");
            return (Criteria) this;
        }

        public Criteria andTjBack1IsNull() {
            addCriterion("tj_back1 is null");
            return (Criteria) this;
        }

        public Criteria andTjBack1IsNotNull() {
            addCriterion("tj_back1 is not null");
            return (Criteria) this;
        }

        public Criteria andTjBack1EqualTo(String value) {
            addCriterion("tj_back1 =", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1NotEqualTo(String value) {
            addCriterion("tj_back1 <>", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1GreaterThan(String value) {
            addCriterion("tj_back1 >", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1GreaterThanOrEqualTo(String value) {
            addCriterion("tj_back1 >=", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1LessThan(String value) {
            addCriterion("tj_back1 <", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1LessThanOrEqualTo(String value) {
            addCriterion("tj_back1 <=", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1Like(String value) {
            addCriterion("tj_back1 like", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1NotLike(String value) {
            addCriterion("tj_back1 not like", value, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1In(List<String> values) {
            addCriterion("tj_back1 in", values, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1NotIn(List<String> values) {
            addCriterion("tj_back1 not in", values, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1Between(String value1, String value2) {
            addCriterion("tj_back1 between", value1, value2, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack1NotBetween(String value1, String value2) {
            addCriterion("tj_back1 not between", value1, value2, "tjBack1");
            return (Criteria) this;
        }

        public Criteria andTjBack2IsNull() {
            addCriterion("tj_back2 is null");
            return (Criteria) this;
        }

        public Criteria andTjBack2IsNotNull() {
            addCriterion("tj_back2 is not null");
            return (Criteria) this;
        }

        public Criteria andTjBack2EqualTo(String value) {
            addCriterion("tj_back2 =", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2NotEqualTo(String value) {
            addCriterion("tj_back2 <>", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2GreaterThan(String value) {
            addCriterion("tj_back2 >", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2GreaterThanOrEqualTo(String value) {
            addCriterion("tj_back2 >=", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2LessThan(String value) {
            addCriterion("tj_back2 <", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2LessThanOrEqualTo(String value) {
            addCriterion("tj_back2 <=", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2Like(String value) {
            addCriterion("tj_back2 like", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2NotLike(String value) {
            addCriterion("tj_back2 not like", value, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2In(List<String> values) {
            addCriterion("tj_back2 in", values, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2NotIn(List<String> values) {
            addCriterion("tj_back2 not in", values, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2Between(String value1, String value2) {
            addCriterion("tj_back2 between", value1, value2, "tjBack2");
            return (Criteria) this;
        }

        public Criteria andTjBack2NotBetween(String value1, String value2) {
            addCriterion("tj_back2 not between", value1, value2, "tjBack2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_job
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 31 15:13:12 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_job
     *
     * @mbg.generated Tue Dec 31 15:13:12 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}