package com.buoyantec.dataobject;

import java.util.Date;

public class tokenDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.tk_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Long tkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.tu_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Long tuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.tk_token
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private String tkToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.tk_buildtime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Date tkBuildtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.tk_expired
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    private Date tkExpired;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public tokenDO(Long tkId, Long tuId, String tkToken, Date tkBuildtime, Date tkExpired) {
        this.tkId = tkId;
        this.tuId = tuId;
        this.tkToken = tkToken;
        this.tkBuildtime = tkBuildtime;
        this.tkExpired = tkExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public tokenDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.tk_id
     *
     * @return the value of t_token.tk_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Long getTkId() {
        return tkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.tk_id
     *
     * @param tkId the value for t_token.tk_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTkId(Long tkId) {
        this.tkId = tkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.tu_id
     *
     * @return the value of t_token.tu_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Long getTuId() {
        return tuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.tu_id
     *
     * @param tuId the value for t_token.tu_id
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTuId(Long tuId) {
        this.tuId = tuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.tk_token
     *
     * @return the value of t_token.tk_token
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public String getTkToken() {
        return tkToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.tk_token
     *
     * @param tkToken the value for t_token.tk_token
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTkToken(String tkToken) {
        this.tkToken = tkToken == null ? null : tkToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.tk_buildtime
     *
     * @return the value of t_token.tk_buildtime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Date getTkBuildtime() {
        return tkBuildtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.tk_buildtime
     *
     * @param tkBuildtime the value for t_token.tk_buildtime
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTkBuildtime(Date tkBuildtime) {
        this.tkBuildtime = tkBuildtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.tk_expired
     *
     * @return the value of t_token.tk_expired
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public Date getTkExpired() {
        return tkExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.tk_expired
     *
     * @param tkExpired the value for t_token.tk_expired
     *
     * @mbg.generated Wed Nov 20 16:34:40 CST 2019
     */
    public void setTkExpired(Date tkExpired) {
        this.tkExpired = tkExpired;
    }
}