package com.buoyantec.dataobject;

import java.util.ArrayList;
import java.util.List;

public class ttwocategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public ttwocategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTtIdIsNull() {
            addCriterion("tt_ID is null");
            return (Criteria) this;
        }

        public Criteria andTtIdIsNotNull() {
            addCriterion("tt_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTtIdEqualTo(Long value) {
            addCriterion("tt_ID =", value, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdNotEqualTo(Long value) {
            addCriterion("tt_ID <>", value, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdGreaterThan(Long value) {
            addCriterion("tt_ID >", value, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tt_ID >=", value, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdLessThan(Long value) {
            addCriterion("tt_ID <", value, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdLessThanOrEqualTo(Long value) {
            addCriterion("tt_ID <=", value, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdIn(List<Long> values) {
            addCriterion("tt_ID in", values, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdNotIn(List<Long> values) {
            addCriterion("tt_ID not in", values, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdBetween(Long value1, Long value2) {
            addCriterion("tt_ID between", value1, value2, "ttId");
            return (Criteria) this;
        }

        public Criteria andTtIdNotBetween(Long value1, Long value2) {
            addCriterion("tt_ID not between", value1, value2, "ttId");
            return (Criteria) this;
        }

        public Criteria andToIdIsNull() {
            addCriterion("to_ID is null");
            return (Criteria) this;
        }

        public Criteria andToIdIsNotNull() {
            addCriterion("to_ID is not null");
            return (Criteria) this;
        }

        public Criteria andToIdEqualTo(String value) {
            addCriterion("to_ID =", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdNotEqualTo(String value) {
            addCriterion("to_ID <>", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdGreaterThan(String value) {
            addCriterion("to_ID >", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdGreaterThanOrEqualTo(String value) {
            addCriterion("to_ID >=", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdLessThan(String value) {
            addCriterion("to_ID <", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdLessThanOrEqualTo(String value) {
            addCriterion("to_ID <=", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdLike(String value) {
            addCriterion("to_ID like", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdNotLike(String value) {
            addCriterion("to_ID not like", value, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdIn(List<String> values) {
            addCriterion("to_ID in", values, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdNotIn(List<String> values) {
            addCriterion("to_ID not in", values, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdBetween(String value1, String value2) {
            addCriterion("to_ID between", value1, value2, "toId");
            return (Criteria) this;
        }

        public Criteria andToIdNotBetween(String value1, String value2) {
            addCriterion("to_ID not between", value1, value2, "toId");
            return (Criteria) this;
        }

        public Criteria andTtNameIsNull() {
            addCriterion("tt_Name is null");
            return (Criteria) this;
        }

        public Criteria andTtNameIsNotNull() {
            addCriterion("tt_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTtNameEqualTo(String value) {
            addCriterion("tt_Name =", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameNotEqualTo(String value) {
            addCriterion("tt_Name <>", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameGreaterThan(String value) {
            addCriterion("tt_Name >", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameGreaterThanOrEqualTo(String value) {
            addCriterion("tt_Name >=", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameLessThan(String value) {
            addCriterion("tt_Name <", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameLessThanOrEqualTo(String value) {
            addCriterion("tt_Name <=", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameLike(String value) {
            addCriterion("tt_Name like", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameNotLike(String value) {
            addCriterion("tt_Name not like", value, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameIn(List<String> values) {
            addCriterion("tt_Name in", values, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameNotIn(List<String> values) {
            addCriterion("tt_Name not in", values, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameBetween(String value1, String value2) {
            addCriterion("tt_Name between", value1, value2, "ttName");
            return (Criteria) this;
        }

        public Criteria andTtNameNotBetween(String value1, String value2) {
            addCriterion("tt_Name not between", value1, value2, "ttName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_twocategory
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 25 17:51:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_twocategory
     *
     * @mbg.generated Wed Dec 25 17:51:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}